/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package molecule.ui.protein.primary;

public abstract class ProteinPrimaryRenderingModePanel_generated extends javax.swing.JPanel implements molecule.ui.protein.primary.signal.ProteinPrimaryApplyRenderingRaiser, molecule.ui.protein.primary.signal.ProteinPrimaryRenderingModeRaiser, star.event.EventController, star.event.Listener
{
	private star.event.Adapter adapter;
	private java.util.prefs.Preferences preferences = null;
	private static final long serialVersionUID = 1L;

	public  ProteinPrimaryRenderingModePanel_generated()
	{
		super();
	}
	 
	public  ProteinPrimaryRenderingModePanel_generated(boolean boolean0)
	{
		super( boolean0);
	}
	 
	public  ProteinPrimaryRenderingModePanel_generated(java.awt.LayoutManager layoutManager, boolean boolean0)
	{
		super( layoutManager,boolean0);
	}
	 
	public  ProteinPrimaryRenderingModePanel_generated(java.awt.LayoutManager layoutManager)
	{
		super( layoutManager);
	}
	 
	public void addNotify()
	{
		super.addNotify();
		getAdapter().addHandled(molecule.ui.protein.tertiary.signal.ProteinTertiaryRenderingModeEvent.class);
	}
	 
	public void eventRaised(final star.event.Event event)
	{
		eventRaisedHandles(event);
	}
	 
	private void eventRaisedHandles(final star.event.Event event)
	{
		if( event.getClass().getName().equals( "molecule.ui.protein.tertiary.signal.ProteinTertiaryRenderingModeEvent" ) && event.isValid() ) 
		{
			 utils.Runner.runOnThread(new Runnable() { public void run() { 
			 long start = System.nanoTime();
			handleProteinTertiaryRenderingModeRaiser( (molecule.ui.protein.tertiary.signal.ProteinTertiaryRenderingModeRaiser)event.getSource());
			 long end = System.nanoTime();
			 if( end - start > 500000000 ) { System.out.println( this.getClass().getName() + ".handleProteinTertiaryRenderingModeRaiser "  + ( end-start )/1000000 ); } }},this,2);
		}
	}
	 
	public star.event.Adapter getAdapter()
	{
		if( adapter == null )
		{
			adapter = new star.event.Adapter(this);
		}
		return adapter;
	}
	 
	public java.util.prefs.Preferences getPreferences(java.lang.String name)
	{
		try
		{
			plugin.preferences.Preferences pref = (plugin.preferences.Preferences) plugin.Loader.getDefaultLoader().getPlugin(plugin.preferences.Preferences.class.getName(), plugin.preferences.PreferencesImplementation.class.getName());
			this.preferences = pref.getPreferences(name);
		}
		catch( plugin.PluginException ex )
		{
			ex.printStackTrace();
		}
		return preferences;
	}
	 
	public java.util.prefs.Preferences getPreferences()
	{
		if( preferences == null )
		{
			try
			{
				plugin.preferences.Preferences pref = (plugin.preferences.Preferences) plugin.Loader.getDefaultLoader().getPlugin(plugin.preferences.Preferences.class.getName(), plugin.preferences.PreferencesImplementation.class.getName());
				this.preferences = pref.getPreferences("molecule.ui.protein.primary.ProteinPrimaryRenderingModePanel");
			}
			catch( plugin.PluginException ex )
			{
				ex.printStackTrace();
			}
		}
		return preferences;
	}
	 
	abstract void handleProteinTertiaryRenderingModeRaiser(molecule.ui.protein.tertiary.signal.ProteinTertiaryRenderingModeRaiser raiser);
	 
	public void raise_ProteinPrimaryApplyRenderingEvent()
	{
		(new molecule.ui.protein.primary.signal.ProteinPrimaryApplyRenderingEvent(this)).raise();
	}
	 
	public void raise_ProteinPrimaryRenderingModeEvent()
	{
		(new molecule.ui.protein.primary.signal.ProteinPrimaryRenderingModeEvent(this)).raise();
	}
	 
	public void removeNotify()
	{
		super.removeNotify();
		getAdapter().removeHandled(molecule.ui.protein.tertiary.signal.ProteinTertiaryRenderingModeEvent.class);
	}
	 
}