/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package molecule.ui.protein.primary;

public abstract class ProteinPrimaryList_generated extends javax.swing.JList implements molecule.ui.protein.primary.signal.ProteinPrimarySelectionRaiser, star.event.EventController, star.event.Listener
{
	private star.event.Adapter adapter;
	private static final long serialVersionUID = 1L;

	public  ProteinPrimaryList_generated()
	{
		super();
	}
	 
	public  ProteinPrimaryList_generated(java.lang.Object[] object)
	{
		super( object);
	}
	 
	public  ProteinPrimaryList_generated(java.util.Vector vector)
	{
		super( vector);
	}
	 
	public  ProteinPrimaryList_generated(javax.swing.ListModel listModel)
	{
		super( listModel);
	}
	 
	public void addNotify()
	{
		super.addNotify();
		getAdapter().addHandled(molecule.ui.protein.tertiary.signal.ProteinTertiarySelectionEvent.class);
	}
	 
	public void eventRaised(final star.event.Event event)
	{
		eventRaisedHandles(event);
	}
	 
	private void eventRaisedHandles(final star.event.Event event)
	{
		if( event.getClass().getName().equals( "molecule.ui.protein.tertiary.signal.ProteinTertiarySelectionEvent" ) && event.isValid() ) 
		{
			 utils.Runner.runOnThread(new Runnable() { public void run() { 
			 long start = System.nanoTime();
			handleProteinTertiarySelectionRaiser( (molecule.ui.protein.tertiary.signal.ProteinTertiarySelectionRaiser)event.getSource());
			 long end = System.nanoTime();
			 if( end - start > 500000000 ) { System.out.println( this.getClass().getName() + ".handleProteinTertiarySelectionRaiser "  + ( end-start )/1000000 ); } }},this,2);
		}
	}
	 
	public star.event.Adapter getAdapter()
	{
		if( adapter == null )
		{
			adapter = new star.event.Adapter(this);
		}
		return adapter;
	}
	 
	abstract void handleProteinTertiarySelectionRaiser(molecule.ui.protein.tertiary.signal.ProteinTertiarySelectionRaiser raiser);
	 
	public void raise_ProteinPrimarySelectionEvent()
	{
		(new molecule.ui.protein.primary.signal.ProteinPrimarySelectionEvent(this)).raise();
	}
	 
	public void removeNotify()
	{
		super.removeNotify();
		getAdapter().removeHandled(molecule.ui.protein.tertiary.signal.ProteinTertiarySelectionEvent.class);
	}
	 
}