/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package molecule.ui.protein.tertiary.properties;

public abstract class ProteinTertiarySizePropertyControls_generated extends molecule.ui.PropertyControls implements molecule.ui.protein.tertiary.signal.ProteinTertiarySizeRaiser, star.event.EventController, star.event.Listener
{
	private static final long serialVersionUID = 1L;

	public  ProteinTertiarySizePropertyControls_generated(java.lang.String string, int int0, int int1, int int2)
	{
		super( string,int0,int1,int2);
	}
	 
	public void addNotify()
	{
		super.addNotify();
		getAdapter().addHandled(molecule.ui.protein.primary.signal.ProteinPrimarySizeEvent.class);
	}
	 
	public void eventRaised(final star.event.Event event)
	{
		eventRaisedHandles(event);
	}
	 
	private void eventRaisedHandles(final star.event.Event event)
	{
		if( event.getClass().getName().equals( "molecule.ui.protein.primary.signal.ProteinPrimarySizeEvent" ) && event.isValid() ) 
		{
			 utils.Runner.runOnThread(new Runnable() { public void run() { 
			 long start = System.nanoTime();
			handleProteinPrimarySizeRaiser( (molecule.ui.protein.primary.signal.ProteinPrimarySizeRaiser)event.getSource());
			 long end = System.nanoTime();
			 if( end - start > 500000000 ) { System.out.println( this.getClass().getName() + ".handleProteinPrimarySizeRaiser "  + ( end-start )/1000000 ); } }},this,2);
		}
	}
	 
	abstract void handleProteinPrimarySizeRaiser(molecule.ui.protein.primary.signal.ProteinPrimarySizeRaiser raiser);
	 
	public void raise_ProteinTertiarySizeEvent()
	{
		(new molecule.ui.protein.tertiary.signal.ProteinTertiarySizeEvent(this)).raise();
	}
	 
	public void removeNotify()
	{
		super.removeNotify();
		getAdapter().removeHandled(molecule.ui.protein.primary.signal.ProteinPrimarySizeEvent.class);
	}
	 
}