/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package molecule.ui.protein.tertiary.properties;

public abstract class ProteinTertiarySSBondSizePropertyControls_generated extends molecule.ui.PropertyControls implements molecule.ui.protein.tertiary.signal.ProteinTertiarySSBondSizeRaiser, star.event.EventController
{
	private static final long serialVersionUID = 1L;

	public  ProteinTertiarySSBondSizePropertyControls_generated(java.lang.String string, int int0, int int1, int int2)
	{
		super( string,int0,int1,int2);
	}
	 
	public void addNotify()
	{
		super.addNotify();
	}
	 
	public void raise_ProteinTertiarySSBondSizeEvent()
	{
		(new molecule.ui.protein.tertiary.signal.ProteinTertiarySSBondSizeEvent(this)).raise();
	}
	 
	public void removeNotify()
	{
		super.removeNotify();
	}
	 
}