/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package molecule.ui.protein.tertiary.properties;

public abstract class ProteinTertiaryHBondSizePropertyControls_generated extends molecule.ui.PropertyControls implements molecule.ui.protein.tertiary.signal.ProteinTertiaryHBondSizeRaiser, star.event.EventController
{
	private static final long serialVersionUID = 1L;

	public  ProteinTertiaryHBondSizePropertyControls_generated(java.lang.String string, int int0, int int1, int int2)
	{
		super( string,int0,int1,int2);
	}
	 
	public void addNotify()
	{
		super.addNotify();
	}
	 
	public void raise_ProteinTertiaryHBondSizeEvent()
	{
		(new molecule.ui.protein.tertiary.signal.ProteinTertiaryHBondSizeEvent(this)).raise();
	}
	 
	public void removeNotify()
	{
		super.removeNotify();
	}
	 
}