/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package molecule.ui.protein.secondary.properties;

public abstract class ProteinSecondarySizePropertyControls_generated extends molecule.ui.PropertyControls implements molecule.ui.protein.secondary.signal.ProteinSecondarySizeRaiser, star.event.EventController
{
	private static final long serialVersionUID = 1L;

	public  ProteinSecondarySizePropertyControls_generated(java.lang.String string, int int0, int int1, int int2)
	{
		super( string,int0,int1,int2);
	}
	 
	public void addNotify()
	{
		super.addNotify();
	}
	 
	public void raise_ProteinSecondarySizeEvent()
	{
		(new molecule.ui.protein.secondary.signal.ProteinSecondarySizeEvent(this)).raise();
	}
	 
	public void removeNotify()
	{
		super.removeNotify();
	}
	 
}