/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package molecule.ui.protein.tertiary.signal;

public class ProteinTertiaryRenderingModeEvent extends star.event.Event
{
	private static final long serialVersionUID = 1L;

	public  ProteinTertiaryRenderingModeEvent(molecule.ui.protein.tertiary.signal.ProteinTertiaryRenderingModeEvent event)
	{
		super( event ) ;
	}
	 
	public  ProteinTertiaryRenderingModeEvent(molecule.ui.protein.tertiary.signal.ProteinTertiaryRenderingModeRaiser raiser)
	{
		super( raiser ) ;
	}
	 
	public  ProteinTertiaryRenderingModeEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public void raise()
	{
		raiseImpl();
	}
	 
}