/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package molecule.ui.protein.tertiary.signal;

public class ProteinTertiaryTranslucencyEvent extends star.event.Event
{
	private static final long serialVersionUID = 1L;

	public  ProteinTertiaryTranslucencyEvent(molecule.ui.protein.tertiary.signal.ProteinTertiaryTranslucencyEvent event)
	{
		super( event ) ;
	}
	 
	public  ProteinTertiaryTranslucencyEvent(molecule.ui.protein.tertiary.signal.ProteinTertiaryTranslucencyRaiser raiser)
	{
		super( raiser ) ;
	}
	 
	public  ProteinTertiaryTranslucencyEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public void raise()
	{
		raiseImpl();
	}
	 
}