/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package molecule.ui.water.signal;

public class WaterSizeEvent extends star.event.Event
{
	private static final long serialVersionUID = 1L;

	public  WaterSizeEvent(molecule.ui.water.signal.WaterSizeEvent event)
	{
		super( event ) ;
	}
	 
	public  WaterSizeEvent(molecule.ui.water.signal.WaterSizeRaiser raiser)
	{
		super( raiser ) ;
	}
	 
	public  WaterSizeEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public void raise()
	{
		raiseImpl();
	}
	 
}