/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package molecule.ui.water.signal;

public class WaterSelectionEvent extends star.event.Event
{
	private static final long serialVersionUID = 1L;

	public  WaterSelectionEvent(molecule.ui.water.signal.WaterSelectionEvent event)
	{
		super( event ) ;
	}
	 
	public  WaterSelectionEvent(molecule.ui.water.signal.WaterSelectionRaiser raiser)
	{
		super( raiser ) ;
	}
	 
	public  WaterSelectionEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public void raise()
	{
		raiseImpl();
	}
	 
}