/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package molecule.ui.adjust.center.protein.secondary;

public abstract class CenterProteinSecondaryPanel_generated extends molecule.ui.AbstractMoleculeUI implements molecule.ui.adjust.center.protein.secondary.signal.CenterProteinSecondaryRaiser, star.event.EventController, star.event.Listener
{
	private java.util.prefs.Preferences preferences = null;
	private static final long serialVersionUID = 1L;

	public  CenterProteinSecondaryPanel_generated()
	{
		super();
	}
	 
	public void addNotify()
	{
		super.addNotify();
		getAdapter().addHandled(molecule.ui.adjust.center.protein.secondary.signal.CenterProteinSecondaryFilterEvent.class);
		getAdapter().addHandled(molecule.ui.adjust.center.protein.secondary.signal.CenterProteinSecondarySelectionEvent.class);
	}
	 
	public void eventRaised(final star.event.Event event)
	{
		eventRaisedHandles(event);
	}
	 
	private void eventRaisedHandles(final star.event.Event event)
	{
		if( event.getClass().getName().equals( "molecule.ui.adjust.center.protein.secondary.signal.CenterProteinSecondaryFilterEvent" ) && event.isValid() ) 
		{
			 utils.Runner.runOnThread(new Runnable() { public void run() { 
			 long start = System.nanoTime();
			handleCenterProteinSecondaryFilterRaiser( (molecule.ui.adjust.center.protein.secondary.signal.CenterProteinSecondaryFilterRaiser)event.getSource());
			 long end = System.nanoTime();
			 if( end - start > 500000000 ) { System.out.println( this.getClass().getName() + ".handleCenterProteinSecondaryFilterRaiser "  + ( end-start )/1000000 ); } }},this,2);
		}if( event.getClass().getName().equals( "molecule.ui.adjust.center.protein.secondary.signal.CenterProteinSecondarySelectionEvent" ) && event.isValid() ) 
		{
			 utils.Runner.runOnThread(new Runnable() { public void run() { 
			 long start = System.nanoTime();
			handleCenterProteinSecondarySelectionRaiser( (molecule.ui.adjust.center.protein.secondary.signal.CenterProteinSecondarySelectionRaiser)event.getSource());
			 long end = System.nanoTime();
			 if( end - start > 500000000 ) { System.out.println( this.getClass().getName() + ".handleCenterProteinSecondarySelectionRaiser "  + ( end-start )/1000000 ); } }},this,2);
		}
	}
	 
	public java.util.prefs.Preferences getPreferences(java.lang.String name)
	{
		try
		{
			plugin.preferences.Preferences pref = (plugin.preferences.Preferences) plugin.Loader.getDefaultLoader().getPlugin(plugin.preferences.Preferences.class.getName(), plugin.preferences.PreferencesImplementation.class.getName());
			this.preferences = pref.getPreferences(name);
		}
		catch( plugin.PluginException ex )
		{
			ex.printStackTrace();
		}
		return preferences;
	}
	 
	public java.util.prefs.Preferences getPreferences()
	{
		if( preferences == null )
		{
			try
			{
				plugin.preferences.Preferences pref = (plugin.preferences.Preferences) plugin.Loader.getDefaultLoader().getPlugin(plugin.preferences.Preferences.class.getName(), plugin.preferences.PreferencesImplementation.class.getName());
				this.preferences = pref.getPreferences("molecule.ui.adjust.center.protein.secondary.CenterProteinSecondaryPanel");
			}
			catch( plugin.PluginException ex )
			{
				ex.printStackTrace();
			}
		}
		return preferences;
	}
	 
	abstract void handleCenterProteinSecondaryFilterRaiser(molecule.ui.adjust.center.protein.secondary.signal.CenterProteinSecondaryFilterRaiser raiser);
	 
	abstract void handleCenterProteinSecondarySelectionRaiser(molecule.ui.adjust.center.protein.secondary.signal.CenterProteinSecondarySelectionRaiser raiser);
	 
	public void raise_CenterProteinSecondaryEvent()
	{
		(new molecule.ui.adjust.center.protein.secondary.signal.CenterProteinSecondaryEvent(this)).raise();
	}
	 
	public void removeNotify()
	{
		super.removeNotify();
		getAdapter().removeHandled(molecule.ui.adjust.center.protein.secondary.signal.CenterProteinSecondaryFilterEvent.class);
		getAdapter().removeHandled(molecule.ui.adjust.center.protein.secondary.signal.CenterProteinSecondarySelectionEvent.class);
	}
	 
}