/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package molecule.ui.hetero.signal;

public class HeteroApplyRenderingEvent extends star.event.Event
{
	private static final long serialVersionUID = 1L;

	public  HeteroApplyRenderingEvent(molecule.ui.hetero.signal.HeteroApplyRenderingEvent event)
	{
		super( event ) ;
	}
	 
	public  HeteroApplyRenderingEvent(molecule.ui.hetero.signal.HeteroApplyRenderingRaiser raiser)
	{
		super( raiser ) ;
	}
	 
	public  HeteroApplyRenderingEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public void raise()
	{
		raiseImpl();
	}
	 
}