/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package molecule.ui.hetero.signal;

public class HeteroHBondSizeEvent extends star.event.Event
{
	private static final long serialVersionUID = 1L;

	public  HeteroHBondSizeEvent(molecule.ui.hetero.signal.HeteroHBondSizeEvent event)
	{
		super( event ) ;
	}
	 
	public  HeteroHBondSizeEvent(molecule.ui.hetero.signal.HeteroHBondSizeRaiser raiser)
	{
		super( raiser ) ;
	}
	 
	public  HeteroHBondSizeEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public void raise()
	{
		raiseImpl();
	}
	 
}