/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package molecule.ui.hetero.signal;

public class HeteroSizeEvent extends star.event.Event
{
	private static final long serialVersionUID = 1L;

	public  HeteroSizeEvent(molecule.ui.hetero.signal.HeteroSizeEvent event)
	{
		super( event ) ;
	}
	 
	public  HeteroSizeEvent(molecule.ui.hetero.signal.HeteroSizeRaiser raiser)
	{
		super( raiser ) ;
	}
	 
	public  HeteroSizeEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public void raise()
	{
		raiseImpl();
	}
	 
}