/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package molecule.ui.hetero.signal;

public class HeteroRenderingModeEvent extends star.event.Event
{
	private static final long serialVersionUID = 1L;

	public  HeteroRenderingModeEvent(molecule.ui.hetero.signal.HeteroRenderingModeEvent event)
	{
		super( event ) ;
	}
	 
	public  HeteroRenderingModeEvent(molecule.ui.hetero.signal.HeteroRenderingModeRaiser raiser)
	{
		super( raiser ) ;
	}
	 
	public  HeteroRenderingModeEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public void raise()
	{
		raiseImpl();
	}
	 
}