/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package molecule.ui.hetero.signal;

public class HeteroSelectionEvent extends star.event.Event
{
	private static final long serialVersionUID = 1L;

	public  HeteroSelectionEvent(molecule.ui.hetero.signal.HeteroSelectionEvent event)
	{
		super( event ) ;
	}
	 
	public  HeteroSelectionEvent(molecule.ui.hetero.signal.HeteroSelectionRaiser raiser)
	{
		super( raiser ) ;
	}
	 
	public  HeteroSelectionEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public void raise()
	{
		raiseImpl();
	}
	 
}