/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package molecule.ui.protein.tertiary.signal;

public class ProteinTertiarySSBondSizeEvent extends star.event.Event
{
	private static final long serialVersionUID = 1L;

	public  ProteinTertiarySSBondSizeEvent(molecule.ui.protein.tertiary.signal.ProteinTertiarySSBondSizeEvent event)
	{
		super( event ) ;
	}
	 
	public  ProteinTertiarySSBondSizeEvent(molecule.ui.protein.tertiary.signal.ProteinTertiarySSBondSizeRaiser raiser)
	{
		super( raiser ) ;
	}
	 
	public  ProteinTertiarySSBondSizeEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public void raise()
	{
		raiseImpl();
	}
	 
}