/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package molecule.ui.protein.tertiary.signal;

public class ProteinTertiaryApplyRenderingEvent extends star.event.Event
{
	private static final long serialVersionUID = 1L;

	public  ProteinTertiaryApplyRenderingEvent(molecule.ui.protein.tertiary.signal.ProteinTertiaryApplyRenderingEvent event)
	{
		super( event ) ;
	}
	 
	public  ProteinTertiaryApplyRenderingEvent(molecule.ui.protein.tertiary.signal.ProteinTertiaryApplyRenderingRaiser raiser)
	{
		super( raiser ) ;
	}
	 
	public  ProteinTertiaryApplyRenderingEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public void raise()
	{
		raiseImpl();
	}
	 
}