/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package molecule.ui.protein.tertiary.signal;

public class ProteinTertiaryHBondSizeEvent extends star.event.Event
{
	private static final long serialVersionUID = 1L;

	public  ProteinTertiaryHBondSizeEvent(molecule.ui.protein.tertiary.signal.ProteinTertiaryHBondSizeEvent event)
	{
		super( event ) ;
	}
	 
	public  ProteinTertiaryHBondSizeEvent(molecule.ui.protein.tertiary.signal.ProteinTertiaryHBondSizeRaiser raiser)
	{
		super( raiser ) ;
	}
	 
	public  ProteinTertiaryHBondSizeEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public void raise()
	{
		raiseImpl();
	}
	 
}