/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package molecule.ui.protein.tertiary.signal;

public class ProteinTertiaryFilterEvent extends star.event.Event
{
	private static final long serialVersionUID = 1L;

	public  ProteinTertiaryFilterEvent(molecule.ui.protein.tertiary.signal.ProteinTertiaryFilterEvent event)
	{
		super( event ) ;
	}
	 
	public  ProteinTertiaryFilterEvent(molecule.ui.protein.tertiary.signal.ProteinTertiaryFilterRaiser raiser)
	{
		super( raiser ) ;
	}
	 
	public  ProteinTertiaryFilterEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public void raise()
	{
		raiseImpl();
	}
	 
}