/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package molecule.ui.protein.tertiary.signal;

public class ProteinTertiarySizeEvent extends star.event.Event
{
	private static final long serialVersionUID = 1L;

	public  ProteinTertiarySizeEvent(molecule.ui.protein.tertiary.signal.ProteinTertiarySizeEvent event)
	{
		super( event ) ;
	}
	 
	public  ProteinTertiarySizeEvent(molecule.ui.protein.tertiary.signal.ProteinTertiarySizeRaiser raiser)
	{
		super( raiser ) ;
	}
	 
	public  ProteinTertiarySizeEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public void raise()
	{
		raiseImpl();
	}
	 
}