/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package molecule.ui.protein.tertiary.signal;

public class ProteinTertiarySSBondTranslucencyEvent extends star.event.Event
{
	private static final long serialVersionUID = 1L;

	public  ProteinTertiarySSBondTranslucencyEvent(molecule.ui.protein.tertiary.signal.ProteinTertiarySSBondTranslucencyEvent event)
	{
		super( event ) ;
	}
	 
	public  ProteinTertiarySSBondTranslucencyEvent(molecule.ui.protein.tertiary.signal.ProteinTertiarySSBondTranslucencyRaiser raiser)
	{
		super( raiser ) ;
	}
	 
	public  ProteinTertiarySSBondTranslucencyEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public void raise()
	{
		raiseImpl();
	}
	 
}