/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package molecule.ui.protein.tertiary.signal;

public class ProteinTertiaryBondTranslucencyEvent extends star.event.Event
{
	private static final long serialVersionUID = 1L;

	public  ProteinTertiaryBondTranslucencyEvent(molecule.ui.protein.tertiary.signal.ProteinTertiaryBondTranslucencyEvent event)
	{
		super( event ) ;
	}
	 
	public  ProteinTertiaryBondTranslucencyEvent(molecule.ui.protein.tertiary.signal.ProteinTertiaryBondTranslucencyRaiser raiser)
	{
		super( raiser ) ;
	}
	 
	public  ProteinTertiaryBondTranslucencyEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public void raise()
	{
		raiseImpl();
	}
	 
}