/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package molecule.ui.protein.tertiary.signal;

public class ProteinTertiaryHBondTranslucencyEvent extends star.event.Event
{
	private static final long serialVersionUID = 1L;

	public  ProteinTertiaryHBondTranslucencyEvent(molecule.ui.protein.tertiary.signal.ProteinTertiaryHBondTranslucencyEvent event)
	{
		super( event ) ;
	}
	 
	public  ProteinTertiaryHBondTranslucencyEvent(molecule.ui.protein.tertiary.signal.ProteinTertiaryHBondTranslucencyRaiser raiser)
	{
		super( raiser ) ;
	}
	 
	public  ProteinTertiaryHBondTranslucencyEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public void raise()
	{
		raiseImpl();
	}
	 
}