/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package molecule.ui.protein.tertiary.signal;

public class ProteinTertiarySelectionEvent extends star.event.Event
{
	private static final long serialVersionUID = 1L;

	public  ProteinTertiarySelectionEvent(molecule.ui.protein.tertiary.signal.ProteinTertiarySelectionEvent event)
	{
		super( event ) ;
	}
	 
	public  ProteinTertiarySelectionEvent(molecule.ui.protein.tertiary.signal.ProteinTertiarySelectionRaiser raiser)
	{
		super( raiser ) ;
	}
	 
	public  ProteinTertiarySelectionEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public void raise()
	{
		raiseImpl();
	}
	 
}