/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package molecule.ui.jmol.signal;

public class HydrogensCalculateEvent extends star.event.Event
{
	private static final long serialVersionUID = 1L;

	public  HydrogensCalculateEvent(molecule.ui.jmol.signal.HydrogensCalculateEvent event)
	{
		super( event ) ;
	}
	 
	public  HydrogensCalculateEvent(molecule.ui.jmol.signal.HydrogensEnableRaiser raiser)
	{
		super( raiser ) ;
	}
	 
	public  HydrogensCalculateEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public void raise()
	{
		raiseImpl();
	}
	 
}