/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package molecule.ui.jmol.signal;

public class HydrogensEnableEvent extends star.event.Event
{
	private static final long serialVersionUID = 1L;

	public  HydrogensEnableEvent(molecule.ui.jmol.signal.HydrogensEnableEvent event)
	{
		super( event ) ;
	}
	 
	public  HydrogensEnableEvent(molecule.ui.jmol.signal.HydrogensEnableRaiser raiser)
	{
		super( raiser ) ;
	}
	 
	public  HydrogensEnableEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public void raise()
	{
		raiseImpl();
	}
	 
}