/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package molecule.ui.jmol.signal;

public class MoleculeJmolUISegmentsEvent extends star.event.Event
{
	private static final long serialVersionUID = 1L;

	public  MoleculeJmolUISegmentsEvent(molecule.ui.jmol.signal.MoleculeJmolUISegmentsEvent event)
	{
		super( event ) ;
	}
	 
	public  MoleculeJmolUISegmentsEvent(molecule.ui.jmol.signal.MoleculeJmolUISegmentsRaiser raiser)
	{
		super( raiser ) ;
	}
	 
	public  MoleculeJmolUISegmentsEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public void raise()
	{
		raiseImpl();
	}
	 
}