/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package molecule.ui.jmol.signal;

public class MoleculeJmolUISpecularEvent extends star.event.Event
{
	private static final long serialVersionUID = 1L;

	public  MoleculeJmolUISpecularEvent(molecule.ui.jmol.signal.MoleculeJmolUISpecularEvent event)
	{
		super( event ) ;
	}
	 
	public  MoleculeJmolUISpecularEvent(molecule.ui.jmol.signal.MoleculeJmolUISpecularRaiser raiser)
	{
		super( raiser ) ;
	}
	 
	public  MoleculeJmolUISpecularEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public void raise()
	{
		raiseImpl();
	}
	 
}