/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package molecule.ui.protein.quaternary.properties;

public abstract class ProteinQuaternarySSBondSizePropertyControls_generated extends molecule.ui.PropertyControls implements molecule.ui.protein.quaternary.signal.ProteinQuaternarySSBondSizeRaiser, star.event.EventController
{
	private static final long serialVersionUID = 1L;

	public  ProteinQuaternarySSBondSizePropertyControls_generated(java.lang.String string, int int0, int int1, int int2)
	{
		super( string,int0,int1,int2);
	}
	 
	public void addNotify()
	{
		super.addNotify();
	}
	 
	public void raise_ProteinQuaternarySSBondSizeEvent()
	{
		(new molecule.ui.protein.quaternary.signal.ProteinQuaternarySSBondSizeEvent(this)).raise();
	}
	 
	public void removeNotify()
	{
		super.removeNotify();
	}
	 
}