/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package molecule.ui.nucleic.properties;

public abstract class NucleicHBondTranslucencyPropertyControls_generated extends molecule.ui.PropertyControls implements molecule.ui.nucleic.signal.NucleicHBondTranslucencyRaiser, star.event.EventController
{
	private static final long serialVersionUID = 1L;

	public  NucleicHBondTranslucencyPropertyControls_generated(java.lang.String string, int int0, int int1, int int2)
	{
		super( string,int0,int1,int2);
	}
	 
	public void addNotify()
	{
		super.addNotify();
	}
	 
	public void raise_NucleicHBondTranslucencyEvent()
	{
		(new molecule.ui.nucleic.signal.NucleicHBondTranslucencyEvent(this)).raise();
	}
	 
	public void removeNotify()
	{
		super.removeNotify();
	}
	 
}