/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package molecule.ui.adjust.signal;

public class RestrictRadiusEvent extends star.event.Event
{
	private static final long serialVersionUID = 1L;

	public  RestrictRadiusEvent(molecule.ui.adjust.signal.RestrictRadiusEvent event)
	{
		super( event ) ;
	}
	 
	public  RestrictRadiusEvent(molecule.ui.adjust.signal.RestrictRadiusRaiser raiser)
	{
		super( raiser ) ;
	}
	 
	public  RestrictRadiusEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public void raise()
	{
		raiseImpl();
	}
	 
}