/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package molecule.ui.adjust.signal;

public class SelectionEvent extends star.event.Event
{
	private static final long serialVersionUID = 1L;

	public  SelectionEvent(molecule.ui.adjust.signal.SelectionEvent event)
	{
		super( event ) ;
	}
	 
	public  SelectionEvent(molecule.ui.adjust.signal.SelectionRaiser raiser)
	{
		super( raiser ) ;
	}
	 
	public  SelectionEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public void raise()
	{
		raiseImpl();
	}
	 
}