/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package molecule.ui.adjust.properties;

public abstract class RestrictRadiusPropertyControls_generated extends molecule.ui.PropertyLogControls implements molecule.ui.adjust.signal.RestrictRadiusRaiser, star.event.EventController
{
	private static final long serialVersionUID = 1L;

	public  RestrictRadiusPropertyControls_generated(java.lang.String string, int int0)
	{
		super( string,int0);
	}
	 
	public void addNotify()
	{
		super.addNotify();
	}
	 
	public void raise_RestrictRadiusEvent()
	{
		(new molecule.ui.adjust.signal.RestrictRadiusEvent(this)).raise();
	}
	 
	public void removeNotify()
	{
		super.removeNotify();
	}
	 
}