/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package molecule.ui.protein.secondary.properties;

public abstract class ProteinSecondaryHBondTranslucencyPropertyControls_generated extends molecule.ui.PropertyControls implements molecule.ui.protein.secondary.signal.ProteinSecondaryHBondTranslucencyRaiser, star.event.EventController
{
	private static final long serialVersionUID = 1L;

	public  ProteinSecondaryHBondTranslucencyPropertyControls_generated(java.lang.String string, int int0, int int1, int int2)
	{
		super( string,int0,int1,int2);
	}
	 
	public void addNotify()
	{
		super.addNotify();
	}
	 
	public void raise_ProteinSecondaryHBondTranslucencyEvent()
	{
		(new molecule.ui.protein.secondary.signal.ProteinSecondaryHBondTranslucencyEvent(this)).raise();
	}
	 
	public void removeNotify()
	{
		super.removeNotify();
	}
	 
}