/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package molecule.ui.adjust.center;

public abstract class CenterPanel_generated extends javax.swing.JTabbedPane implements star.event.EventController, star.event.Listener
{
	private star.event.Adapter adapter;
	private java.util.prefs.Preferences preferences = null;
	private static final long serialVersionUID = 1L;

	public  CenterPanel_generated()
	{
		super();
	}
	 
	public  CenterPanel_generated(int int0, int int1)
	{
		super( int0,int1);
	}
	 
	public  CenterPanel_generated(int int0)
	{
		super( int0);
	}
	 
	public void addNotify()
	{
		super.addNotify();
		getAdapter().addHandled(molecule.ui.adjust.center.water.signal.CenterWaterSelectionEvent.class);
		getAdapter().addHandled(molecule.ui.adjust.center.hetero.signal.CenterHeteroSelectionEvent.class);
		getAdapter().addHandled(molecule.ui.adjust.center.nucleic.signal.CenterNucleicSelectionEvent.class);
	}
	 
	public void eventRaised(final star.event.Event event)
	{
		eventRaisedHandles(event);
	}
	 
	private void eventRaisedHandles(final star.event.Event event)
	{
		if( event.getClass().getName().equals( "molecule.ui.adjust.center.water.signal.CenterWaterSelectionEvent" ) && event.isValid() ) 
		{
			 utils.Runner.runOnThread(new Runnable() { public void run() { 
			 long start = System.nanoTime();
			handleCenterWaterSelectionRaiser( (molecule.ui.adjust.center.water.signal.CenterWaterSelectionRaiser)event.getSource());
			 long end = System.nanoTime();
			 if( end - start > 500000000 ) { System.out.println( this.getClass().getName() + ".handleCenterWaterSelectionRaiser "  + ( end-start )/1000000 ); } }},this,2);
		}if( event.getClass().getName().equals( "molecule.ui.adjust.center.hetero.signal.CenterHeteroSelectionEvent" ) && event.isValid() ) 
		{
			 utils.Runner.runOnThread(new Runnable() { public void run() { 
			 long start = System.nanoTime();
			handleCenterHeteroSelectionRaiser( (molecule.ui.adjust.center.hetero.signal.CenterHeteroSelectionRaiser)event.getSource());
			 long end = System.nanoTime();
			 if( end - start > 500000000 ) { System.out.println( this.getClass().getName() + ".handleCenterHeteroSelectionRaiser "  + ( end-start )/1000000 ); } }},this,2);
		}if( event.getClass().getName().equals( "molecule.ui.adjust.center.nucleic.signal.CenterNucleicSelectionEvent" ) && event.isValid() ) 
		{
			 utils.Runner.runOnThread(new Runnable() { public void run() { 
			 long start = System.nanoTime();
			handleCenterNucleicSelectionRaiser( (molecule.ui.adjust.center.nucleic.signal.CenterNucleicSelectionRaiser)event.getSource());
			 long end = System.nanoTime();
			 if( end - start > 500000000 ) { System.out.println( this.getClass().getName() + ".handleCenterNucleicSelectionRaiser "  + ( end-start )/1000000 ); } }},this,2);
		}
	}
	 
	public star.event.Adapter getAdapter()
	{
		if( adapter == null )
		{
			adapter = new star.event.Adapter(this);
		}
		return adapter;
	}
	 
	public java.util.prefs.Preferences getPreferences(java.lang.String name)
	{
		try
		{
			plugin.preferences.Preferences pref = (plugin.preferences.Preferences) plugin.Loader.getDefaultLoader().getPlugin(plugin.preferences.Preferences.class.getName(), plugin.preferences.PreferencesImplementation.class.getName());
			this.preferences = pref.getPreferences(name);
		}
		catch( plugin.PluginException ex )
		{
			ex.printStackTrace();
		}
		return preferences;
	}
	 
	public java.util.prefs.Preferences getPreferences()
	{
		if( preferences == null )
		{
			try
			{
				plugin.preferences.Preferences pref = (plugin.preferences.Preferences) plugin.Loader.getDefaultLoader().getPlugin(plugin.preferences.Preferences.class.getName(), plugin.preferences.PreferencesImplementation.class.getName());
				this.preferences = pref.getPreferences("molecule.ui.adjust.center.CenterPanel");
			}
			catch( plugin.PluginException ex )
			{
				ex.printStackTrace();
			}
		}
		return preferences;
	}
	 
	abstract void handleCenterHeteroSelectionRaiser(molecule.ui.adjust.center.hetero.signal.CenterHeteroSelectionRaiser raiser);
	 
	abstract void handleCenterNucleicSelectionRaiser(molecule.ui.adjust.center.nucleic.signal.CenterNucleicSelectionRaiser raiser);
	 
	abstract void handleCenterWaterSelectionRaiser(molecule.ui.adjust.center.water.signal.CenterWaterSelectionRaiser raiser);
	 
	public void removeNotify()
	{
		super.removeNotify();
		getAdapter().removeHandled(molecule.ui.adjust.center.water.signal.CenterWaterSelectionEvent.class);
		getAdapter().removeHandled(molecule.ui.adjust.center.hetero.signal.CenterHeteroSelectionEvent.class);
		getAdapter().removeHandled(molecule.ui.adjust.center.nucleic.signal.CenterNucleicSelectionEvent.class);
	}
	 
}