/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package molecule.ui.jmol.properties;

public abstract class MoleculeJmolUISpecularPropertyControls_generated extends molecule.ui.PropertyControls implements molecule.ui.jmol.signal.MoleculeJmolUISpecularRaiser, star.event.EventController
{
	private static final long serialVersionUID = 1L;

	public  MoleculeJmolUISpecularPropertyControls_generated(java.lang.String string, int int0, int int1, int int2)
	{
		super( string,int0,int1,int2);
	}
	 
	public void addNotify()
	{
		super.addNotify();
	}
	 
	public void raise_MoleculeJmolUISpecularEvent()
	{
		(new molecule.ui.jmol.signal.MoleculeJmolUISpecularEvent(this)).raise();
	}
	 
	public void removeNotify()
	{
		super.removeNotify();
	}
	 
}