/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package molecule.ui.protein.secondary;

public abstract class ProteinSecondaryPanel_generated extends molecule.ui.AbstractMoleculeUI implements molecule.ui.signal.RenderingInfoRaiser, star.event.EventController, star.event.Listener
{
	private java.util.prefs.Preferences preferences = null;
	private static final long serialVersionUID = 1L;

	public  ProteinSecondaryPanel_generated()
	{
		super();
	}
	 
	public void addNotify()
	{
		super.addNotify();
		getAdapter().addHandled(molecule.ui.protein.secondary.signal.ProteinSecondaryHBondSizeEvent.class);
		getAdapter().addHandled(molecule.ui.protein.secondary.signal.ProteinSecondaryRenderingModeEvent.class);
		getAdapter().addHandled(molecule.ui.protein.secondary.signal.ProteinSecondarySelectionEvent.class);
		getAdapter().addHandled(molecule.ui.protein.secondary.signal.ProteinSecondaryFilterEvent.class);
		getAdapter().addHandled(molecule.ui.protein.secondary.signal.ProteinSecondaryApplyRenderingEvent.class);
		getAdapter().addHandled(molecule.ui.protein.secondary.signal.ProteinSecondaryHBondTranslucencyEvent.class);
		getAdapter().addHandled(molecule.ui.protein.secondary.signal.ProteinSecondarySizeEvent.class);
	}
	 
	public void eventRaised(final star.event.Event event)
	{
		eventRaisedHandles(event);
	}
	 
	private void eventRaisedHandles(final star.event.Event event)
	{
		if( event.getClass().getName().equals( "molecule.ui.protein.secondary.signal.ProteinSecondaryHBondSizeEvent" ) && event.isValid() ) 
		{
			 utils.Runner.runOnThread(new Runnable() { public void run() { 
			 long start = System.nanoTime();
			handleProteinSecondaryHBondSizeRaiser( (molecule.ui.protein.secondary.signal.ProteinSecondaryHBondSizeRaiser)event.getSource());
			 long end = System.nanoTime();
			 if( end - start > 500000000 ) { System.out.println( this.getClass().getName() + ".handleProteinSecondaryHBondSizeRaiser "  + ( end-start )/1000000 ); } }},this,2);
		}if( event.getClass().getName().equals( "molecule.ui.protein.secondary.signal.ProteinSecondaryRenderingModeEvent" ) && event.isValid() ) 
		{
			 utils.Runner.runOnThread(new Runnable() { public void run() { 
			 long start = System.nanoTime();
			handleProteinSecondaryRenderingModeRaiser( (molecule.ui.protein.secondary.signal.ProteinSecondaryRenderingModeRaiser)event.getSource());
			 long end = System.nanoTime();
			 if( end - start > 500000000 ) { System.out.println( this.getClass().getName() + ".handleProteinSecondaryRenderingModeRaiser "  + ( end-start )/1000000 ); } }},this,2);
		}if( event.getClass().getName().equals( "molecule.ui.protein.secondary.signal.ProteinSecondarySelectionEvent" ) && event.isValid() ) 
		{
			 utils.Runner.runOnThread(new Runnable() { public void run() { 
			 long start = System.nanoTime();
			handleProteinSecondarySelectionRaiser( (molecule.ui.protein.secondary.signal.ProteinSecondarySelectionRaiser)event.getSource());
			 long end = System.nanoTime();
			 if( end - start > 500000000 ) { System.out.println( this.getClass().getName() + ".handleProteinSecondarySelectionRaiser "  + ( end-start )/1000000 ); } }},this,2);
		}if( event.getClass().getName().equals( "molecule.ui.protein.secondary.signal.ProteinSecondaryFilterEvent" ) && event.isValid() ) 
		{
			 utils.Runner.runOnThread(new Runnable() { public void run() { 
			 long start = System.nanoTime();
			handleProteinSecondaryFilterRaiser( (molecule.ui.protein.secondary.signal.ProteinSecondaryFilterRaiser)event.getSource());
			 long end = System.nanoTime();
			 if( end - start > 500000000 ) { System.out.println( this.getClass().getName() + ".handleProteinSecondaryFilterRaiser "  + ( end-start )/1000000 ); } }},this,2);
		}if( event.getClass().getName().equals( "molecule.ui.protein.secondary.signal.ProteinSecondaryApplyRenderingEvent" ) && event.isValid() ) 
		{
			 utils.Runner.runOnThread(new Runnable() { public void run() { 
			 long start = System.nanoTime();
			handleProteinSecondaryApplyRenderingRaiser( (molecule.ui.protein.secondary.signal.ProteinSecondaryApplyRenderingRaiser)event.getSource());
			 long end = System.nanoTime();
			 if( end - start > 500000000 ) { System.out.println( this.getClass().getName() + ".handleProteinSecondaryApplyRenderingRaiser "  + ( end-start )/1000000 ); } }},this,2);
		}if( event.getClass().getName().equals( "molecule.ui.protein.secondary.signal.ProteinSecondaryHBondTranslucencyEvent" ) && event.isValid() ) 
		{
			 utils.Runner.runOnThread(new Runnable() { public void run() { 
			 long start = System.nanoTime();
			handleProteinSecondaryHBondTranslucencyRaiser( (molecule.ui.protein.secondary.signal.ProteinSecondaryHBondTranslucencyRaiser)event.getSource());
			 long end = System.nanoTime();
			 if( end - start > 500000000 ) { System.out.println( this.getClass().getName() + ".handleProteinSecondaryHBondTranslucencyRaiser "  + ( end-start )/1000000 ); } }},this,2);
		}if( event.getClass().getName().equals( "molecule.ui.protein.secondary.signal.ProteinSecondarySizeEvent" ) && event.isValid() ) 
		{
			 utils.Runner.runOnThread(new Runnable() { public void run() { 
			 long start = System.nanoTime();
			handleProteinSecondarySizeRaiser( (molecule.ui.protein.secondary.signal.ProteinSecondarySizeRaiser)event.getSource());
			 long end = System.nanoTime();
			 if( end - start > 500000000 ) { System.out.println( this.getClass().getName() + ".handleProteinSecondarySizeRaiser "  + ( end-start )/1000000 ); } }},this,2);
		}
	}
	 
	public java.util.prefs.Preferences getPreferences(java.lang.String name)
	{
		try
		{
			plugin.preferences.Preferences pref = (plugin.preferences.Preferences) plugin.Loader.getDefaultLoader().getPlugin(plugin.preferences.Preferences.class.getName(), plugin.preferences.PreferencesImplementation.class.getName());
			this.preferences = pref.getPreferences(name);
		}
		catch( plugin.PluginException ex )
		{
			ex.printStackTrace();
		}
		return preferences;
	}
	 
	public java.util.prefs.Preferences getPreferences()
	{
		if( preferences == null )
		{
			try
			{
				plugin.preferences.Preferences pref = (plugin.preferences.Preferences) plugin.Loader.getDefaultLoader().getPlugin(plugin.preferences.Preferences.class.getName(), plugin.preferences.PreferencesImplementation.class.getName());
				this.preferences = pref.getPreferences("molecule.ui.protein.secondary.ProteinSecondaryPanel");
			}
			catch( plugin.PluginException ex )
			{
				ex.printStackTrace();
			}
		}
		return preferences;
	}
	 
	abstract void handleProteinSecondaryApplyRenderingRaiser(molecule.ui.protein.secondary.signal.ProteinSecondaryApplyRenderingRaiser raiser);
	 
	abstract void handleProteinSecondaryFilterRaiser(molecule.ui.protein.secondary.signal.ProteinSecondaryFilterRaiser raiser);
	 
	abstract void handleProteinSecondaryHBondSizeRaiser(molecule.ui.protein.secondary.signal.ProteinSecondaryHBondSizeRaiser raiser);
	 
	abstract void handleProteinSecondaryHBondTranslucencyRaiser(molecule.ui.protein.secondary.signal.ProteinSecondaryHBondTranslucencyRaiser raiser);
	 
	abstract void handleProteinSecondaryRenderingModeRaiser(molecule.ui.protein.secondary.signal.ProteinSecondaryRenderingModeRaiser raiser);
	 
	abstract void handleProteinSecondarySelectionRaiser(molecule.ui.protein.secondary.signal.ProteinSecondarySelectionRaiser raiser);
	 
	abstract void handleProteinSecondarySizeRaiser(molecule.ui.protein.secondary.signal.ProteinSecondarySizeRaiser raiser);
	 
	public void raise_RenderingInfoEvent()
	{
		(new molecule.ui.signal.RenderingInfoEvent(this)).raise();
	}
	 
	public void removeNotify()
	{
		super.removeNotify();
		getAdapter().removeHandled(molecule.ui.protein.secondary.signal.ProteinSecondaryHBondSizeEvent.class);
		getAdapter().removeHandled(molecule.ui.protein.secondary.signal.ProteinSecondaryRenderingModeEvent.class);
		getAdapter().removeHandled(molecule.ui.protein.secondary.signal.ProteinSecondarySelectionEvent.class);
		getAdapter().removeHandled(molecule.ui.protein.secondary.signal.ProteinSecondaryFilterEvent.class);
		getAdapter().removeHandled(molecule.ui.protein.secondary.signal.ProteinSecondaryApplyRenderingEvent.class);
		getAdapter().removeHandled(molecule.ui.protein.secondary.signal.ProteinSecondaryHBondTranslucencyEvent.class);
		getAdapter().removeHandled(molecule.ui.protein.secondary.signal.ProteinSecondarySizeEvent.class);
	}
	 
}