/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package molecule.ui.protein.secondary;

public abstract class ProteinSecondaryList_generated extends javax.swing.JList implements molecule.ui.protein.secondary.signal.ProteinSecondarySelectionRaiser, star.event.EventController, star.event.Listener
{
	private star.event.Adapter adapter;
	private java.util.prefs.Preferences preferences = null;
	private static final long serialVersionUID = 1L;

	public  ProteinSecondaryList_generated()
	{
		super();
	}
	 
	public  ProteinSecondaryList_generated(java.lang.Object[] object)
	{
		super( object);
	}
	 
	public  ProteinSecondaryList_generated(java.util.Vector vector)
	{
		super( vector);
	}
	 
	public  ProteinSecondaryList_generated(javax.swing.ListModel listModel)
	{
		super( listModel);
	}
	 
	public void addNotify()
	{
		super.addNotify();
		getAdapter().addHandled(molecule.ui.protein.secondary.signal.ProteinSecondaryFilterEvent.class);
	}
	 
	public void eventRaised(final star.event.Event event)
	{
		eventRaisedHandles(event);
	}
	 
	private void eventRaisedHandles(final star.event.Event event)
	{
		if( event.getClass().getName().equals( "molecule.ui.protein.secondary.signal.ProteinSecondaryFilterEvent" ) && event.isValid() ) 
		{
			 utils.Runner.runOnThread(new Runnable() { public void run() { 
			 long start = System.nanoTime();
			handleProteinSecondaryFilterRaiser( (molecule.ui.protein.secondary.signal.ProteinSecondaryFilterRaiser)event.getSource());
			 long end = System.nanoTime();
			 if( end - start > 500000000 ) { System.out.println( this.getClass().getName() + ".handleProteinSecondaryFilterRaiser "  + ( end-start )/1000000 ); } }},this,2);
		}
	}
	 
	public star.event.Adapter getAdapter()
	{
		if( adapter == null )
		{
			adapter = new star.event.Adapter(this);
		}
		return adapter;
	}
	 
	public java.util.prefs.Preferences getPreferences(java.lang.String name)
	{
		try
		{
			plugin.preferences.Preferences pref = (plugin.preferences.Preferences) plugin.Loader.getDefaultLoader().getPlugin(plugin.preferences.Preferences.class.getName(), plugin.preferences.PreferencesImplementation.class.getName());
			this.preferences = pref.getPreferences(name);
		}
		catch( plugin.PluginException ex )
		{
			ex.printStackTrace();
		}
		return preferences;
	}
	 
	public java.util.prefs.Preferences getPreferences()
	{
		if( preferences == null )
		{
			try
			{
				plugin.preferences.Preferences pref = (plugin.preferences.Preferences) plugin.Loader.getDefaultLoader().getPlugin(plugin.preferences.Preferences.class.getName(), plugin.preferences.PreferencesImplementation.class.getName());
				this.preferences = pref.getPreferences("molecule.ui.protein.secondary.ProteinSecondaryList");
			}
			catch( plugin.PluginException ex )
			{
				ex.printStackTrace();
			}
		}
		return preferences;
	}
	 
	abstract void handleProteinSecondaryFilterRaiser(molecule.ui.protein.secondary.signal.ProteinSecondaryFilterRaiser raiser);
	 
	public void raise_ProteinSecondarySelectionEvent()
	{
		(new molecule.ui.protein.secondary.signal.ProteinSecondarySelectionEvent(this)).raise();
	}
	 
	public void removeNotify()
	{
		super.removeNotify();
		getAdapter().removeHandled(molecule.ui.protein.secondary.signal.ProteinSecondaryFilterEvent.class);
	}
	 
}