/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package molecule.ui.adjust.center.nucleic;

public abstract class CenterNucleicList_generated extends javax.swing.JList implements molecule.ui.adjust.center.nucleic.signal.CenterNucleicSelectionRaiser, star.event.EventController
{
	private star.event.Adapter adapter;
	private static final long serialVersionUID = 1L;

	public  CenterNucleicList_generated()
	{
		super();
	}
	 
	public  CenterNucleicList_generated(java.lang.Object[] object)
	{
		super( object);
	}
	 
	public  CenterNucleicList_generated(java.util.Vector vector)
	{
		super( vector);
	}
	 
	public  CenterNucleicList_generated(javax.swing.ListModel listModel)
	{
		super( listModel);
	}
	 
	public void addNotify()
	{
		super.addNotify();
	}
	 
	public star.event.Adapter getAdapter()
	{
		if( adapter == null )
		{
			adapter = new star.event.Adapter(this);
		}
		return adapter;
	}
	 
	public void raise_CenterNucleicSelectionEvent()
	{
		(new molecule.ui.adjust.center.nucleic.signal.CenterNucleicSelectionEvent(this)).raise();
	}
	 
	public void removeNotify()
	{
		super.removeNotify();
	}
	 
}