/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package events;

public class ErrorDialogEvent extends star.event.Event
{
	private static final long serialVersionUID = 1L;

	public  ErrorDialogEvent(events.ErrorDialogEvent event)
	{
		super( event ) ;
	}
	 
	public  ErrorDialogEvent(events.ErrorDialogRaiser raiser)
	{
		super( raiser ) ;
	}
	 
	public  ErrorDialogEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public void raise()
	{
		raiseImpl();
	}
	 
}