/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package molecule.ui.nucleic.signal;

public class NucleicBondTranslucencyEvent extends star.event.Event
{
	private static final long serialVersionUID = 1L;

	public  NucleicBondTranslucencyEvent(molecule.ui.nucleic.signal.NucleicBondTranslucencyEvent event)
	{
		super( event ) ;
	}
	 
	public  NucleicBondTranslucencyEvent(molecule.ui.nucleic.signal.NucleicBondTranslucencyRaiser raiser)
	{
		super( raiser ) ;
	}
	 
	public  NucleicBondTranslucencyEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public void raise()
	{
		raiseImpl();
	}
	 
}