/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package molecule.ui.nucleic.signal;

public class NucleicRenderingModeEvent extends star.event.Event
{
	private static final long serialVersionUID = 1L;

	public  NucleicRenderingModeEvent(molecule.ui.nucleic.signal.NucleicRenderingModeEvent event)
	{
		super( event ) ;
	}
	 
	public  NucleicRenderingModeEvent(molecule.ui.nucleic.signal.NucleicRenderingModeRaiser raiser)
	{
		super( raiser ) ;
	}
	 
	public  NucleicRenderingModeEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public void raise()
	{
		raiseImpl();
	}
	 
}