/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package molecule.ui.nucleic.signal;

public class NucleicHBondTranslucencyEvent extends star.event.Event
{
	private static final long serialVersionUID = 1L;

	public  NucleicHBondTranslucencyEvent(molecule.ui.nucleic.signal.NucleicHBondTranslucencyEvent event)
	{
		super( event ) ;
	}
	 
	public  NucleicHBondTranslucencyEvent(molecule.ui.nucleic.signal.NucleicHBondTranslucencyRaiser raiser)
	{
		super( raiser ) ;
	}
	 
	public  NucleicHBondTranslucencyEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public void raise()
	{
		raiseImpl();
	}
	 
}