/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package molecule.ui.nucleic.signal;

public class NucleicSizeEvent extends star.event.Event
{
	private static final long serialVersionUID = 1L;

	public  NucleicSizeEvent(molecule.ui.nucleic.signal.NucleicSizeEvent event)
	{
		super( event ) ;
	}
	 
	public  NucleicSizeEvent(molecule.ui.nucleic.signal.NucleicSizeRaiser raiser)
	{
		super( raiser ) ;
	}
	 
	public  NucleicSizeEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public void raise()
	{
		raiseImpl();
	}
	 
}