/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package molecule.ui.nucleic.signal;

public class NucleicHBondSizeEvent extends star.event.Event
{
	private static final long serialVersionUID = 1L;

	public  NucleicHBondSizeEvent(molecule.ui.nucleic.signal.NucleicHBondSizeEvent event)
	{
		super( event ) ;
	}
	 
	public  NucleicHBondSizeEvent(molecule.ui.nucleic.signal.NucleicHBondSizeRaiser raiser)
	{
		super( raiser ) ;
	}
	 
	public  NucleicHBondSizeEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public void raise()
	{
		raiseImpl();
	}
	 
}