/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package molecule.ui.protein.primary.signal;

public class ProteinPrimaryBondTranslucencyEvent extends star.event.Event
{
	private static final long serialVersionUID = 1L;

	public  ProteinPrimaryBondTranslucencyEvent(molecule.ui.protein.primary.signal.ProteinPrimaryBondTranslucencyEvent event)
	{
		super( event ) ;
	}
	 
	public  ProteinPrimaryBondTranslucencyEvent(molecule.ui.protein.primary.signal.ProteinPrimaryBondTranslucencyRaiser raiser)
	{
		super( raiser ) ;
	}
	 
	public  ProteinPrimaryBondTranslucencyEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public void raise()
	{
		raiseImpl();
	}
	 
}