/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package molecule.ui.protein.primary.signal;

public class ProteinPrimarySelectionEvent extends star.event.Event
{
	private static final long serialVersionUID = 1L;

	public  ProteinPrimarySelectionEvent(molecule.ui.protein.primary.signal.ProteinPrimarySelectionEvent event)
	{
		super( event ) ;
	}
	 
	public  ProteinPrimarySelectionEvent(molecule.ui.protein.primary.signal.ProteinPrimarySelectionRaiser raiser)
	{
		super( raiser ) ;
	}
	 
	public  ProteinPrimarySelectionEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public void raise()
	{
		raiseImpl();
	}
	 
}