/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package molecule.ui.protein.primary.signal;

public class ProteinPrimarySizeEvent extends star.event.Event
{
	private static final long serialVersionUID = 1L;

	public  ProteinPrimarySizeEvent(molecule.ui.protein.primary.signal.ProteinPrimarySizeEvent event)
	{
		super( event ) ;
	}
	 
	public  ProteinPrimarySizeEvent(molecule.ui.protein.primary.signal.ProteinPrimarySizeRaiser raiser)
	{
		super( raiser ) ;
	}
	 
	public  ProteinPrimarySizeEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public void raise()
	{
		raiseImpl();
	}
	 
}