/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package molecule.ui.protein.primary.signal;

public class ProteinPrimaryApplyRenderingEvent extends star.event.Event
{
	private static final long serialVersionUID = 1L;

	public  ProteinPrimaryApplyRenderingEvent(molecule.ui.protein.primary.signal.ProteinPrimaryApplyRenderingEvent event)
	{
		super( event ) ;
	}
	 
	public  ProteinPrimaryApplyRenderingEvent(molecule.ui.protein.primary.signal.ProteinPrimaryApplyRenderingRaiser raiser)
	{
		super( raiser ) ;
	}
	 
	public  ProteinPrimaryApplyRenderingEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public void raise()
	{
		raiseImpl();
	}
	 
}