/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package molecule.ui.adjust.center.protein.quaternary.signal;

public class CenterProteinQuaternaryEvent extends molecule.ui.adjust.signal.SelectionEvent
{
	private static final long serialVersionUID = 1L;

	public  CenterProteinQuaternaryEvent(molecule.ui.adjust.center.protein.quaternary.signal.CenterProteinQuaternaryEvent event)
	{
		super( event ) ;
	}
	 
	public  CenterProteinQuaternaryEvent(molecule.ui.adjust.center.protein.quaternary.signal.CenterProteinQuaternaryRaiser raiser)
	{
		super( raiser ) ;
	}
	 
	public  CenterProteinQuaternaryEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public void raise()
	{
		raiseImpl();
	}
	 
}