/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package molecule.ui.adjust.center.protein.quaternary.signal;

public class CenterProteinQuaternarySelectionEvent extends molecule.ui.adjust.signal.SelectionEvent
{
	private static final long serialVersionUID = 1L;

	public  CenterProteinQuaternarySelectionEvent(molecule.ui.adjust.center.protein.quaternary.signal.CenterProteinQuaternarySelectionEvent event)
	{
		super( event ) ;
	}
	 
	public  CenterProteinQuaternarySelectionEvent(molecule.ui.adjust.center.protein.quaternary.signal.CenterProteinQuaternarySelectionRaiser raiser)
	{
		super( raiser ) ;
	}
	 
	public  CenterProteinQuaternarySelectionEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public void raise()
	{
		raiseImpl();
	}
	 
}