/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package molecule.ui.adjust.center.water.signal;

public class CenterWaterSelectionEvent extends molecule.ui.adjust.signal.SelectionEvent
{
	private static final long serialVersionUID = 1L;

	public  CenterWaterSelectionEvent(molecule.ui.adjust.center.water.signal.CenterWaterSelectionEvent event)
	{
		super( event ) ;
	}
	 
	public  CenterWaterSelectionEvent(molecule.ui.adjust.center.water.signal.CenterWaterSelectionRaiser raiser)
	{
		super( raiser ) ;
	}
	 
	public  CenterWaterSelectionEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public void raise()
	{
		raiseImpl();
	}
	 
}