/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package molecule.ui.jmol.signal;

public class MoleculeEvent extends star.event.Event
{
	private static final long serialVersionUID = 1L;

	public  MoleculeEvent(molecule.ui.jmol.signal.MoleculeEvent event)
	{
		super( event ) ;
	}
	 
	public  MoleculeEvent(molecule.ui.jmol.signal.MoleculeRaiser raiser)
	{
		super( raiser ) ;
	}
	 
	public  MoleculeEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public void raise()
	{
		raiseImpl();
	}
	 
}