/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package molecule.ui.jmol.signal;

public class MoleculeJmolUIBrightnessEvent extends star.event.Event
{
	private static final long serialVersionUID = 1L;

	public  MoleculeJmolUIBrightnessEvent(molecule.ui.jmol.signal.MoleculeJmolUIBrightnessEvent event)
	{
		super( event ) ;
	}
	 
	public  MoleculeJmolUIBrightnessEvent(molecule.ui.jmol.signal.MoleculeJmolUIBrightnessRaiser raiser)
	{
		super( raiser ) ;
	}
	 
	public  MoleculeJmolUIBrightnessEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public void raise()
	{
		raiseImpl();
	}
	 
}