/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package molecule.ui.jmol.signal;

public class SSBondsEnableEvent extends star.event.Event
{
	private static final long serialVersionUID = 1L;

	public  SSBondsEnableEvent(molecule.ui.jmol.signal.SSBondsEnableEvent event)
	{
		super( event ) ;
	}
	 
	public  SSBondsEnableEvent(molecule.ui.jmol.signal.SSBondsEnableRaiser raiser)
	{
		super( raiser ) ;
	}
	 
	public  SSBondsEnableEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public void raise()
	{
		raiseImpl();
	}
	 
}