/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package molecule.ui.protein.secondary.signal;

public class ProteinSecondaryApplyRenderingEvent extends star.event.Event
{
	private static final long serialVersionUID = 1L;

	public  ProteinSecondaryApplyRenderingEvent(molecule.ui.protein.secondary.signal.ProteinSecondaryApplyRenderingEvent event)
	{
		super( event ) ;
	}
	 
	public  ProteinSecondaryApplyRenderingEvent(molecule.ui.protein.secondary.signal.ProteinSecondaryApplyRenderingRaiser raiser)
	{
		super( raiser ) ;
	}
	 
	public  ProteinSecondaryApplyRenderingEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public void raise()
	{
		raiseImpl();
	}
	 
}