/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package molecule.ui.protein.secondary.signal;

public class ProteinSecondaryHBondTranslucencyEvent extends star.event.Event
{
	private static final long serialVersionUID = 1L;

	public  ProteinSecondaryHBondTranslucencyEvent(molecule.ui.protein.secondary.signal.ProteinSecondaryHBondTranslucencyEvent event)
	{
		super( event ) ;
	}
	 
	public  ProteinSecondaryHBondTranslucencyEvent(molecule.ui.protein.secondary.signal.ProteinSecondaryHBondTranslucencyRaiser raiser)
	{
		super( raiser ) ;
	}
	 
	public  ProteinSecondaryHBondTranslucencyEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public void raise()
	{
		raiseImpl();
	}
	 
}