/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package molecule.ui.protein.secondary.signal;

public class ProteinSecondarySizeEvent extends star.event.Event
{
	private static final long serialVersionUID = 1L;

	public  ProteinSecondarySizeEvent(molecule.ui.protein.secondary.signal.ProteinSecondarySizeEvent event)
	{
		super( event ) ;
	}
	 
	public  ProteinSecondarySizeEvent(molecule.ui.protein.secondary.signal.ProteinSecondarySizeRaiser raiser)
	{
		super( raiser ) ;
	}
	 
	public  ProteinSecondarySizeEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public void raise()
	{
		raiseImpl();
	}
	 
}