/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package molecule.ui.protein.secondary.signal;

public class ProteinSecondaryRenderingModeEvent extends star.event.Event
{
	private static final long serialVersionUID = 1L;

	public  ProteinSecondaryRenderingModeEvent(molecule.ui.protein.secondary.signal.ProteinSecondaryRenderingModeEvent event)
	{
		super( event ) ;
	}
	 
	public  ProteinSecondaryRenderingModeEvent(molecule.ui.protein.secondary.signal.ProteinSecondaryRenderingModeRaiser raiser)
	{
		super( raiser ) ;
	}
	 
	public  ProteinSecondaryRenderingModeEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public void raise()
	{
		raiseImpl();
	}
	 
}