/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package molecule.ui.hetero.signal;

public class HeteroBondTranslucencyEvent extends star.event.Event
{
	private static final long serialVersionUID = 1L;

	public  HeteroBondTranslucencyEvent(molecule.ui.hetero.signal.HeteroBondTranslucencyEvent event)
	{
		super( event ) ;
	}
	 
	public  HeteroBondTranslucencyEvent(molecule.ui.hetero.signal.HeteroBondTranslucencyRaiser raiser)
	{
		super( raiser ) ;
	}
	 
	public  HeteroBondTranslucencyEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public void raise()
	{
		raiseImpl();
	}
	 
}