/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package molecule.ui.adjust.center.protein.tertiary;

public abstract class CenterProteinTertiaryList_generated extends javax.swing.JList implements molecule.ui.adjust.center.protein.tertiary.signal.CenterProteinTertiarySelectionRaiser, star.event.EventController, star.event.Listener
{
	private star.event.Adapter adapter;
	private static final long serialVersionUID = 1L;

	public  CenterProteinTertiaryList_generated()
	{
		super();
	}
	 
	public  CenterProteinTertiaryList_generated(java.lang.Object[] object)
	{
		super( object);
	}
	 
	public  CenterProteinTertiaryList_generated(java.util.Vector vector)
	{
		super( vector);
	}
	 
	public  CenterProteinTertiaryList_generated(javax.swing.ListModel listModel)
	{
		super( listModel);
	}
	 
	public void addNotify()
	{
		super.addNotify();
		getAdapter().addHandled(molecule.ui.adjust.center.protein.tertiary.signal.CenterProteinTertiaryFilterEvent.class);
	}
	 
	public void eventRaised(final star.event.Event event)
	{
		eventRaisedHandles(event);
	}
	 
	private void eventRaisedHandles(final star.event.Event event)
	{
		if( event.getClass().getName().equals( "molecule.ui.adjust.center.protein.tertiary.signal.CenterProteinTertiaryFilterEvent" ) && event.isValid() ) 
		{
			 utils.Runner.runOnThread(new Runnable() { public void run() { 
			 long start = System.nanoTime();
			handleCenterProteinTertiaryFilterRaiser( (molecule.ui.adjust.center.protein.tertiary.signal.CenterProteinTertiaryFilterRaiser)event.getSource());
			 long end = System.nanoTime();
			 if( end - start > 500000000 ) { System.out.println( this.getClass().getName() + ".handleCenterProteinTertiaryFilterRaiser "  + ( end-start )/1000000 ); } }},this,2);
		}
	}
	 
	public star.event.Adapter getAdapter()
	{
		if( adapter == null )
		{
			adapter = new star.event.Adapter(this);
		}
		return adapter;
	}
	 
	abstract void handleCenterProteinTertiaryFilterRaiser(molecule.ui.adjust.center.protein.tertiary.signal.CenterProteinTertiaryFilterRaiser raiser);
	 
	public void raise_CenterProteinTertiarySelectionEvent()
	{
		(new molecule.ui.adjust.center.protein.tertiary.signal.CenterProteinTertiarySelectionEvent(this)).raise();
	}
	 
	public void removeNotify()
	{
		super.removeNotify();
		getAdapter().removeHandled(molecule.ui.adjust.center.protein.tertiary.signal.CenterProteinTertiaryFilterEvent.class);
	}
	 
}