/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package molecule.ui.adjust.center.protein.tertiary;

public abstract class CenterProteinTertiaryPanel_generated extends molecule.ui.AbstractMoleculeUI implements molecule.ui.adjust.center.protein.tertiary.signal.CenterProteinTertiaryRaiser, star.event.EventController, star.event.Listener
{
	private java.util.prefs.Preferences preferences = null;
	private static final long serialVersionUID = 1L;

	public  CenterProteinTertiaryPanel_generated()
	{
		super();
	}
	 
	public void addNotify()
	{
		super.addNotify();
		getAdapter().addHandled(molecule.ui.adjust.center.protein.tertiary.signal.CenterProteinTertiarySelectionEvent.class);
		getAdapter().addHandled(molecule.ui.adjust.center.protein.tertiary.signal.CenterProteinTertiaryFilterEvent.class);
	}
	 
	public void eventRaised(final star.event.Event event)
	{
		eventRaisedHandles(event);
	}
	 
	private void eventRaisedHandles(final star.event.Event event)
	{
		if( event.getClass().getName().equals( "molecule.ui.adjust.center.protein.tertiary.signal.CenterProteinTertiarySelectionEvent" ) && event.isValid() ) 
		{
			 utils.Runner.runOnThread(new Runnable() { public void run() { 
			 long start = System.nanoTime();
			handleCenterProteinTertiarySelectionRaiser( (molecule.ui.adjust.center.protein.tertiary.signal.CenterProteinTertiarySelectionRaiser)event.getSource());
			 long end = System.nanoTime();
			 if( end - start > 500000000 ) { System.out.println( this.getClass().getName() + ".handleCenterProteinTertiarySelectionRaiser "  + ( end-start )/1000000 ); } }},this,2);
		}if( event.getClass().getName().equals( "molecule.ui.adjust.center.protein.tertiary.signal.CenterProteinTertiaryFilterEvent" ) && event.isValid() ) 
		{
			 utils.Runner.runOnThread(new Runnable() { public void run() { 
			 long start = System.nanoTime();
			handleCenterProteinTertiaryFilterRaiser( (molecule.ui.adjust.center.protein.tertiary.signal.CenterProteinTertiaryFilterRaiser)event.getSource());
			 long end = System.nanoTime();
			 if( end - start > 500000000 ) { System.out.println( this.getClass().getName() + ".handleCenterProteinTertiaryFilterRaiser "  + ( end-start )/1000000 ); } }},this,2);
		}
	}
	 
	public java.util.prefs.Preferences getPreferences(java.lang.String name)
	{
		try
		{
			plugin.preferences.Preferences pref = (plugin.preferences.Preferences) plugin.Loader.getDefaultLoader().getPlugin(plugin.preferences.Preferences.class.getName(), plugin.preferences.PreferencesImplementation.class.getName());
			this.preferences = pref.getPreferences(name);
		}
		catch( plugin.PluginException ex )
		{
			ex.printStackTrace();
		}
		return preferences;
	}
	 
	public java.util.prefs.Preferences getPreferences()
	{
		if( preferences == null )
		{
			try
			{
				plugin.preferences.Preferences pref = (plugin.preferences.Preferences) plugin.Loader.getDefaultLoader().getPlugin(plugin.preferences.Preferences.class.getName(), plugin.preferences.PreferencesImplementation.class.getName());
				this.preferences = pref.getPreferences("molecule.ui.adjust.center.protein.tertiary.CenterProteinTertiaryPanel");
			}
			catch( plugin.PluginException ex )
			{
				ex.printStackTrace();
			}
		}
		return preferences;
	}
	 
	abstract void handleCenterProteinTertiaryFilterRaiser(molecule.ui.adjust.center.protein.tertiary.signal.CenterProteinTertiaryFilterRaiser raiser);
	 
	abstract void handleCenterProteinTertiarySelectionRaiser(molecule.ui.adjust.center.protein.tertiary.signal.CenterProteinTertiarySelectionRaiser raiser);
	 
	public void raise_CenterProteinTertiaryEvent()
	{
		(new molecule.ui.adjust.center.protein.tertiary.signal.CenterProteinTertiaryEvent(this)).raise();
	}
	 
	public void removeNotify()
	{
		super.removeNotify();
		getAdapter().removeHandled(molecule.ui.adjust.center.protein.tertiary.signal.CenterProteinTertiarySelectionEvent.class);
		getAdapter().removeHandled(molecule.ui.adjust.center.protein.tertiary.signal.CenterProteinTertiaryFilterEvent.class);
	}
	 
}