/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package molecule.ui.adjust.center.nucleic;

public abstract class CenterNucleicPanel_generated extends molecule.ui.AbstractMoleculeUI implements molecule.ui.adjust.center.nucleic.signal.CenterNucleicRaiser, star.event.EventController, star.event.Listener
{
	private java.util.prefs.Preferences preferences = null;
	private static final long serialVersionUID = 1L;

	public  CenterNucleicPanel_generated()
	{
		super();
	}
	 
	public void addNotify()
	{
		super.addNotify();
		getAdapter().addHandled(molecule.ui.adjust.center.nucleic.signal.CenterNucleicFilterEvent.class);
		getAdapter().addHandled(molecule.ui.adjust.center.nucleic.signal.CenterNucleicSelectionEvent.class);
	}
	 
	public void eventRaised(final star.event.Event event)
	{
		eventRaisedHandles(event);
	}
	 
	private void eventRaisedHandles(final star.event.Event event)
	{
		if( event.getClass().getName().equals( "molecule.ui.adjust.center.nucleic.signal.CenterNucleicFilterEvent" ) && event.isValid() ) 
		{
			 utils.Runner.runOnThread(new Runnable() { public void run() { 
			 long start = System.nanoTime();
			handleCenterNucleicFilterRaiser( (molecule.ui.adjust.center.nucleic.signal.CenterNucleicFilterRaiser)event.getSource());
			 long end = System.nanoTime();
			 if( end - start > 500000000 ) { System.out.println( this.getClass().getName() + ".handleCenterNucleicFilterRaiser "  + ( end-start )/1000000 ); } }},this,2);
		}if( event.getClass().getName().equals( "molecule.ui.adjust.center.nucleic.signal.CenterNucleicSelectionEvent" ) && event.isValid() ) 
		{
			 utils.Runner.runOnThread(new Runnable() { public void run() { 
			 long start = System.nanoTime();
			handleCenterNucleicSelectionRaiser( (molecule.ui.adjust.center.nucleic.signal.CenterNucleicSelectionRaiser)event.getSource());
			 long end = System.nanoTime();
			 if( end - start > 500000000 ) { System.out.println( this.getClass().getName() + ".handleCenterNucleicSelectionRaiser "  + ( end-start )/1000000 ); } }},this,2);
		}
	}
	 
	public java.util.prefs.Preferences getPreferences(java.lang.String name)
	{
		try
		{
			plugin.preferences.Preferences pref = (plugin.preferences.Preferences) plugin.Loader.getDefaultLoader().getPlugin(plugin.preferences.Preferences.class.getName(), plugin.preferences.PreferencesImplementation.class.getName());
			this.preferences = pref.getPreferences(name);
		}
		catch( plugin.PluginException ex )
		{
			ex.printStackTrace();
		}
		return preferences;
	}
	 
	public java.util.prefs.Preferences getPreferences()
	{
		if( preferences == null )
		{
			try
			{
				plugin.preferences.Preferences pref = (plugin.preferences.Preferences) plugin.Loader.getDefaultLoader().getPlugin(plugin.preferences.Preferences.class.getName(), plugin.preferences.PreferencesImplementation.class.getName());
				this.preferences = pref.getPreferences("molecule.ui.adjust.center.nucleic.CenterNucleicPanel");
			}
			catch( plugin.PluginException ex )
			{
				ex.printStackTrace();
			}
		}
		return preferences;
	}
	 
	abstract void handleCenterNucleicFilterRaiser(molecule.ui.adjust.center.nucleic.signal.CenterNucleicFilterRaiser raiser);
	 
	abstract void handleCenterNucleicSelectionRaiser(molecule.ui.adjust.center.nucleic.signal.CenterNucleicSelectionRaiser raiser);
	 
	public void raise_CenterNucleicEvent()
	{
		(new molecule.ui.adjust.center.nucleic.signal.CenterNucleicEvent(this)).raise();
	}
	 
	public void removeNotify()
	{
		super.removeNotify();
		getAdapter().removeHandled(molecule.ui.adjust.center.nucleic.signal.CenterNucleicFilterEvent.class);
		getAdapter().removeHandled(molecule.ui.adjust.center.nucleic.signal.CenterNucleicSelectionEvent.class);
	}
	 
}