/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package molecule.ui.protein.quaternary;

public abstract class ProteinQuaternaryRenderingProperties_generated extends molecule.ui.AbstractAtomRenderingProperties implements star.event.EventController
{
	private static final long serialVersionUID = 1L;

	public  ProteinQuaternaryRenderingProperties_generated()
	{
		super();
	}
	 
	public void addNotify()
	{
		super.addNotify();
	}
	 
	public void removeNotify()
	{
		super.removeNotify();
	}
	 
}