/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package molecule.ui;

public abstract class MoleculeUIContainer_generated extends javax.swing.JTabbedPane implements star.event.EventController
{
	private star.event.Adapter adapter;
	private static final long serialVersionUID = 1L;

	public  MoleculeUIContainer_generated()
	{
		super();
	}
	 
	public  MoleculeUIContainer_generated(int int0, int int1)
	{
		super( int0,int1);
	}
	 
	public  MoleculeUIContainer_generated(int int0)
	{
		super( int0);
	}
	 
	public void addNotify()
	{
		super.addNotify();
	}
	 
	public star.event.Adapter getAdapter()
	{
		if( adapter == null )
		{
			adapter = new star.event.Adapter(this);
		}
		return adapter;
	}
	 
	public void removeNotify()
	{
		super.removeNotify();
	}
	 
}