/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package molecule.ui.signal;

public class AdjustInfoEvent extends star.event.Event
{
	private static final long serialVersionUID = 1L;

	public  AdjustInfoEvent(molecule.ui.signal.AdjustInfoEvent event)
	{
		super( event ) ;
	}
	 
	public  AdjustInfoEvent(molecule.ui.signal.AdjustInfoRaiser raiser)
	{
		super( raiser ) ;
	}
	 
	public  AdjustInfoEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public void raise()
	{
		raiseImpl();
	}
	 
}