/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package molecule.ui.signal;

public class MoleculeJmolRenderingPropertiesEvent extends star.event.Event
{
	private static final long serialVersionUID = 1L;

	public  MoleculeJmolRenderingPropertiesEvent(molecule.ui.signal.MoleculeJmolRenderingPropertiesEvent event)
	{
		super( event ) ;
	}
	 
	public  MoleculeJmolRenderingPropertiesEvent(molecule.ui.signal.MoleculeJmolRenderingPropertiesRaiser raiser)
	{
		super( raiser ) ;
	}
	 
	public  MoleculeJmolRenderingPropertiesEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public void raise()
	{
		raiseImpl();
	}
	 
}