/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package molecule.ui.adjust.center.nucleic.signal;

public class CenterNucleicSelectionEvent extends molecule.ui.adjust.signal.SelectionEvent
{
	private static final long serialVersionUID = 1L;

	public  CenterNucleicSelectionEvent(molecule.ui.adjust.center.nucleic.signal.CenterNucleicSelectionEvent event)
	{
		super( event ) ;
	}
	 
	public  CenterNucleicSelectionEvent(molecule.ui.adjust.center.nucleic.signal.CenterNucleicSelectionRaiser raiser)
	{
		super( raiser ) ;
	}
	 
	public  CenterNucleicSelectionEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public void raise()
	{
		raiseImpl();
	}
	 
}