/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package molecule.ui.adjust.center.nucleic.signal;

public class CenterNucleicFilterEvent extends star.event.Event
{
	private static final long serialVersionUID = 1L;

	public  CenterNucleicFilterEvent(molecule.ui.adjust.center.nucleic.signal.CenterNucleicFilterEvent event)
	{
		super( event ) ;
	}
	 
	public  CenterNucleicFilterEvent(molecule.ui.adjust.center.nucleic.signal.CenterNucleicFilterRaiser raiser)
	{
		super( raiser ) ;
	}
	 
	public  CenterNucleicFilterEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public void raise()
	{
		raiseImpl();
	}
	 
}