/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package app.signal;

public class AdditionalStructuresInfoEvent extends star.event.Event
{
	private static final long serialVersionUID = 1L;

	public  AdditionalStructuresInfoEvent(app.signal.AdditionalStructuresInfoEvent event)
	{
		super( event ) ;
	}
	 
	public  AdditionalStructuresInfoEvent(app.signal.ViewHydrogensRaiser raiser)
	{
		super( raiser ) ;
	}
	 
	public  AdditionalStructuresInfoEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public void raise()
	{
		raiseImpl();
	}
	 
}