/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package app.signal;

public class CloseMoleculeEvent extends star.event.Event
{
	private static final long serialVersionUID = 1L;

	public  CloseMoleculeEvent(app.signal.CloseMoleculeEvent event)
	{
		super( event ) ;
	}
	 
	public  CloseMoleculeEvent(app.signal.CloseMoleculeRaiser raiser)
	{
		super( raiser ) ;
	}
	 
	public  CloseMoleculeEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public void raise()
	{
		raiseImpl();
	}
	 
}