/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package app.signal;

public class FileSaveImageEvent extends star.event.Event
{
	private static final long serialVersionUID = 1L;

	public  FileSaveImageEvent(app.signal.FileSaveImageEvent event)
	{
		super( event ) ;
	}
	 
	public  FileSaveImageEvent(app.signal.FileSaveImageRaiser raiser)
	{
		super( raiser ) ;
	}
	 
	public  FileSaveImageEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public void raise()
	{
		raiseImpl();
	}
	 
}