/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package app.signal;

public class MoleculesBackgroundColorEvent extends star.event.Event
{
	private static final long serialVersionUID = 1L;

	public  MoleculesBackgroundColorEvent(app.signal.MoleculesBackgroundColorEvent event)
	{
		super( event ) ;
	}
	 
	public  MoleculesBackgroundColorEvent(app.signal.MoleculesBackgroundColorRaiser raiser)
	{
		super( raiser ) ;
	}
	 
	public  MoleculesBackgroundColorEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public void raise()
	{
		raiseImpl();
	}
	 
}