/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package app.signal;

public class ResetAllMoleculesEvent extends star.event.Event
{
	private static final long serialVersionUID = 1L;

	public  ResetAllMoleculesEvent(app.signal.ResetAllMoleculesEvent event)
	{
		super( event ) ;
	}
	 
	public  ResetAllMoleculesEvent(app.signal.ResetAllMoleculesRaiser raiser)
	{
		super( raiser ) ;
	}
	 
	public  ResetAllMoleculesEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public void raise()
	{
		raiseImpl();
	}
	 
}