/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package app.signal;

public class ResetMoleculeEvent extends star.event.Event
{
	private static final long serialVersionUID = 1L;

	public  ResetMoleculeEvent(app.signal.ResetMoleculeEvent event)
	{
		super( event ) ;
	}
	 
	public  ResetMoleculeEvent(app.signal.ResetMoleculeRaiser raiser)
	{
		super( raiser ) ;
	}
	 
	public  ResetMoleculeEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public void raise()
	{
		raiseImpl();
	}
	 
}