/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package app.signal;

public class SampleOpenEvent extends star.event.Event
{
	private static final long serialVersionUID = 1L;

	public  SampleOpenEvent(app.signal.SampleOpenEvent event)
	{
		super( event ) ;
	}
	 
	public  SampleOpenEvent(app.signal.SampleOpenRaiser raiser)
	{
		super( raiser ) ;
	}
	 
	public  SampleOpenEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public void raise()
	{
		raiseImpl();
	}
	 
}