/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package app.signal;

public class ViewStructureOptionsEvent extends star.event.Event
{
	private static final long serialVersionUID = 1L;

	public  ViewStructureOptionsEvent(app.signal.ViewStructureOptionsEvent event)
	{
		super( event ) ;
	}
	 
	public  ViewStructureOptionsEvent(app.signal.ViewStructureOptionsRaiser raiser)
	{
		super( raiser ) ;
	}
	 
	public  ViewStructureOptionsEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public void raise()
	{
		raiseImpl();
	}
	 
}