/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package app.signal;

public class ViewForegroundColorEvent extends star.event.Event
{
	private static final long serialVersionUID = 1L;

	public  ViewForegroundColorEvent(app.signal.ViewForegroundColorEvent event)
	{
		super( event ) ;
	}
	 
	public  ViewForegroundColorEvent(app.signal.ViewForegroundColorRaiser raiser)
	{
		super( raiser ) ;
	}
	 
	public  ViewForegroundColorEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public void raise()
	{
		raiseImpl();
	}
	 
}