/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package molecule.ui.adjust.center.protein.secondary.signal;

public class CenterProteinSecondaryEvent extends molecule.ui.adjust.signal.SelectionEvent
{
	private static final long serialVersionUID = 1L;

	public  CenterProteinSecondaryEvent(molecule.ui.adjust.center.protein.secondary.signal.CenterProteinSecondaryEvent event)
	{
		super( event ) ;
	}
	 
	public  CenterProteinSecondaryEvent(molecule.ui.adjust.center.protein.secondary.signal.CenterProteinSecondaryRaiser raiser)
	{
		super( raiser ) ;
	}
	 
	public  CenterProteinSecondaryEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public void raise()
	{
		raiseImpl();
	}
	 
}