/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package molecule.ui.adjust.center.protein.secondary.signal;

public class CenterProteinSecondaryFilterEvent extends star.event.Event
{
	private static final long serialVersionUID = 1L;

	public  CenterProteinSecondaryFilterEvent(molecule.ui.adjust.center.protein.secondary.signal.CenterProteinSecondaryFilterEvent event)
	{
		super( event ) ;
	}
	 
	public  CenterProteinSecondaryFilterEvent(molecule.ui.adjust.center.protein.secondary.signal.CenterProteinSecondaryFilterRaiser raiser)
	{
		super( raiser ) ;
	}
	 
	public  CenterProteinSecondaryFilterEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public void raise()
	{
		raiseImpl();
	}
	 
}