/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package molecule.ui.adjust.center.protein.secondary.signal;

public class CenterProteinSecondarySelectionEvent extends molecule.ui.adjust.signal.SelectionEvent
{
	private static final long serialVersionUID = 1L;

	public  CenterProteinSecondarySelectionEvent(molecule.ui.adjust.center.protein.secondary.signal.CenterProteinSecondarySelectionEvent event)
	{
		super( event ) ;
	}
	 
	public  CenterProteinSecondarySelectionEvent(molecule.ui.adjust.center.protein.secondary.signal.CenterProteinSecondarySelectionRaiser raiser)
	{
		super( raiser ) ;
	}
	 
	public  CenterProteinSecondarySelectionEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public void raise()
	{
		raiseImpl();
	}
	 
}