/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package molecule.ui.adjust.center.protein.quaternary;

public abstract class CenterProteinQuaternaryList_generated extends javax.swing.JList implements molecule.ui.adjust.center.protein.quaternary.signal.CenterProteinQuaternarySelectionRaiser, star.event.EventController
{
	private star.event.Adapter adapter;
	private static final long serialVersionUID = 1L;

	public  CenterProteinQuaternaryList_generated()
	{
		super();
	}
	 
	public  CenterProteinQuaternaryList_generated(java.lang.Object[] object)
	{
		super( object);
	}
	 
	public  CenterProteinQuaternaryList_generated(java.util.Vector vector)
	{
		super( vector);
	}
	 
	public  CenterProteinQuaternaryList_generated(javax.swing.ListModel listModel)
	{
		super( listModel);
	}
	 
	public void addNotify()
	{
		super.addNotify();
	}
	 
	public star.event.Adapter getAdapter()
	{
		if( adapter == null )
		{
			adapter = new star.event.Adapter(this);
		}
		return adapter;
	}
	 
	public void raise_CenterProteinQuaternarySelectionEvent()
	{
		(new molecule.ui.adjust.center.protein.quaternary.signal.CenterProteinQuaternarySelectionEvent(this)).raise();
	}
	 
	public void removeNotify()
	{
		super.removeNotify();
	}
	 
}