/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package molecule.ui.nucleic;

public abstract class NucleicHBondRenderingProperties_generated extends molecule.ui.AbstractAtomRenderingProperties implements star.event.EventController
{
	private static final long serialVersionUID = 1L;

	public  NucleicHBondRenderingProperties_generated()
	{
		super();
	}
	 
	public void addNotify()
	{
		super.addNotify();
	}
	 
	public void removeNotify()
	{
		super.removeNotify();
	}
	 
}