/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package molecule.ui.structureoptions.center.foreground;

public abstract class MoleculeJmolRenderingPropertiesPanel_generated extends javax.swing.JPanel implements molecule.ui.signal.RenderingInfoRaiser, star.event.EventController, star.event.Listener
{
	private star.event.Adapter adapter;
	private java.util.prefs.Preferences preferences = null;
	private static final long serialVersionUID = 1L;

	public  MoleculeJmolRenderingPropertiesPanel_generated()
	{
		super();
	}
	 
	public  MoleculeJmolRenderingPropertiesPanel_generated(boolean boolean0)
	{
		super( boolean0);
	}
	 
	public  MoleculeJmolRenderingPropertiesPanel_generated(java.awt.LayoutManager layoutManager, boolean boolean0)
	{
		super( layoutManager,boolean0);
	}
	 
	public  MoleculeJmolRenderingPropertiesPanel_generated(java.awt.LayoutManager layoutManager)
	{
		super( layoutManager);
	}
	 
	public void addNotify()
	{
		super.addNotify();
		getAdapter().addHandled(molecule.ui.jmol.signal.MoleculeJmolUISpecularEvent.class);
		getAdapter().addHandled(molecule.ui.jmol.signal.MoleculeJmolUIDiffuseEvent.class);
		getAdapter().addHandled(molecule.ui.jmol.signal.MoleculeJmolUISegmentsEvent.class);
		getAdapter().addHandled(molecule.ui.jmol.signal.MoleculeJmolUIBrightnessEvent.class);
	}
	 
	public void eventRaised(final star.event.Event event)
	{
		eventRaisedHandles(event);
	}
	 
	private void eventRaisedHandles(final star.event.Event event)
	{
		if( event.getClass().getName().equals( "molecule.ui.jmol.signal.MoleculeJmolUISpecularEvent" ) && event.isValid() ) 
		{
			 utils.Runner.runOnThread(new Runnable() { public void run() { 
			 long start = System.nanoTime();
			handleMoleculeJmolUISpecularRaiser( (molecule.ui.jmol.signal.MoleculeJmolUISpecularRaiser)event.getSource());
			 long end = System.nanoTime();
			 if( end - start > 500000000 ) { System.out.println( this.getClass().getName() + ".handleMoleculeJmolUISpecularRaiser "  + ( end-start )/1000000 ); } }},this,2);
		}if( event.getClass().getName().equals( "molecule.ui.jmol.signal.MoleculeJmolUIDiffuseEvent" ) && event.isValid() ) 
		{
			 utils.Runner.runOnThread(new Runnable() { public void run() { 
			 long start = System.nanoTime();
			handleMoleculeJmolUIDiffuseRaiser( (molecule.ui.jmol.signal.MoleculeJmolUIDiffuseRaiser)event.getSource());
			 long end = System.nanoTime();
			 if( end - start > 500000000 ) { System.out.println( this.getClass().getName() + ".handleMoleculeJmolUIDiffuseRaiser "  + ( end-start )/1000000 ); } }},this,2);
		}if( event.getClass().getName().equals( "molecule.ui.jmol.signal.MoleculeJmolUISegmentsEvent" ) && event.isValid() ) 
		{
			 utils.Runner.runOnThread(new Runnable() { public void run() { 
			 long start = System.nanoTime();
			handleMoleculeJmolUISegmentsRaiser( (molecule.ui.jmol.signal.MoleculeJmolUISegmentsRaiser)event.getSource());
			 long end = System.nanoTime();
			 if( end - start > 500000000 ) { System.out.println( this.getClass().getName() + ".handleMoleculeJmolUISegmentsRaiser "  + ( end-start )/1000000 ); } }},this,2);
		}if( event.getClass().getName().equals( "molecule.ui.jmol.signal.MoleculeJmolUIBrightnessEvent" ) && event.isValid() ) 
		{
			 utils.Runner.runOnThread(new Runnable() { public void run() { 
			 long start = System.nanoTime();
			handleMoleculeJmolUIBrightnessRaiser( (molecule.ui.jmol.signal.MoleculeJmolUIBrightnessRaiser)event.getSource());
			 long end = System.nanoTime();
			 if( end - start > 500000000 ) { System.out.println( this.getClass().getName() + ".handleMoleculeJmolUIBrightnessRaiser "  + ( end-start )/1000000 ); } }},this,2);
		}
	}
	 
	public star.event.Adapter getAdapter()
	{
		if( adapter == null )
		{
			adapter = new star.event.Adapter(this);
		}
		return adapter;
	}
	 
	public java.util.prefs.Preferences getPreferences(java.lang.String name)
	{
		try
		{
			plugin.preferences.Preferences pref = (plugin.preferences.Preferences) plugin.Loader.getDefaultLoader().getPlugin(plugin.preferences.Preferences.class.getName(), plugin.preferences.PreferencesImplementation.class.getName());
			this.preferences = pref.getPreferences(name);
		}
		catch( plugin.PluginException ex )
		{
			ex.printStackTrace();
		}
		return preferences;
	}
	 
	public java.util.prefs.Preferences getPreferences()
	{
		if( preferences == null )
		{
			try
			{
				plugin.preferences.Preferences pref = (plugin.preferences.Preferences) plugin.Loader.getDefaultLoader().getPlugin(plugin.preferences.Preferences.class.getName(), plugin.preferences.PreferencesImplementation.class.getName());
				this.preferences = pref.getPreferences("molecule.ui.structureoptions.center.foreground.MoleculeJmolRenderingPropertiesPanel");
			}
			catch( plugin.PluginException ex )
			{
				ex.printStackTrace();
			}
		}
		return preferences;
	}
	 
	abstract void handleMoleculeJmolUIBrightnessRaiser(molecule.ui.jmol.signal.MoleculeJmolUIBrightnessRaiser raiser);
	 
	abstract void handleMoleculeJmolUIDiffuseRaiser(molecule.ui.jmol.signal.MoleculeJmolUIDiffuseRaiser raiser);
	 
	abstract void handleMoleculeJmolUISegmentsRaiser(molecule.ui.jmol.signal.MoleculeJmolUISegmentsRaiser raiser);
	 
	abstract void handleMoleculeJmolUISpecularRaiser(molecule.ui.jmol.signal.MoleculeJmolUISpecularRaiser raiser);
	 
	public void raise_RenderingInfoEvent()
	{
		(new molecule.ui.signal.RenderingInfoEvent(this)).raise();
	}
	 
	public void removeNotify()
	{
		super.removeNotify();
		getAdapter().removeHandled(molecule.ui.jmol.signal.MoleculeJmolUISpecularEvent.class);
		getAdapter().removeHandled(molecule.ui.jmol.signal.MoleculeJmolUIDiffuseEvent.class);
		getAdapter().removeHandled(molecule.ui.jmol.signal.MoleculeJmolUISegmentsEvent.class);
		getAdapter().removeHandled(molecule.ui.jmol.signal.MoleculeJmolUIBrightnessEvent.class);
	}
	 
}