/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package molecule.ui.hetero;

public abstract class HeteroAtomsRenderingProperties_generated extends molecule.ui.AbstractAtomRenderingProperties implements star.event.EventController
{
	private static final long serialVersionUID = 1L;

	public  HeteroAtomsRenderingProperties_generated()
	{
		super();
	}
	 
	public void addNotify()
	{
		super.addNotify();
	}
	 
	public void removeNotify()
	{
		super.removeNotify();
	}
	 
}