/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package molecule.ui.protein.secondary.signal;

public class ProteinSecondaryFilterEvent extends star.event.Event
{
	private static final long serialVersionUID = 1L;

	public  ProteinSecondaryFilterEvent(molecule.ui.protein.secondary.signal.ProteinSecondaryFilterEvent event)
	{
		super( event ) ;
	}
	 
	public  ProteinSecondaryFilterEvent(molecule.ui.protein.secondary.signal.ProteinSecondaryFilterRaiser raiser)
	{
		super( raiser ) ;
	}
	 
	public  ProteinSecondaryFilterEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public void raise()
	{
		raiseImpl();
	}
	 
}