/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package molecule.ui.protein.secondary.signal;

public class ProteinSecondaryHBondSizeEvent extends star.event.Event
{
	private static final long serialVersionUID = 1L;

	public  ProteinSecondaryHBondSizeEvent(molecule.ui.protein.secondary.signal.ProteinSecondaryHBondSizeEvent event)
	{
		super( event ) ;
	}
	 
	public  ProteinSecondaryHBondSizeEvent(molecule.ui.protein.secondary.signal.ProteinSecondaryHBondSizeRaiser raiser)
	{
		super( raiser ) ;
	}
	 
	public  ProteinSecondaryHBondSizeEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public void raise()
	{
		raiseImpl();
	}
	 
}