/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package molecule.ui.adjust.center.protein.tertiary.signal;

public class CenterProteinTertiarySelectionEvent extends molecule.ui.adjust.signal.SelectionEvent
{
	private static final long serialVersionUID = 1L;

	public  CenterProteinTertiarySelectionEvent(molecule.ui.adjust.center.protein.tertiary.signal.CenterProteinTertiarySelectionEvent event)
	{
		super( event ) ;
	}
	 
	public  CenterProteinTertiarySelectionEvent(molecule.ui.adjust.center.protein.tertiary.signal.CenterProteinTertiarySelectionRaiser raiser)
	{
		super( raiser ) ;
	}
	 
	public  CenterProteinTertiarySelectionEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public void raise()
	{
		raiseImpl();
	}
	 
}