/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package molecule.ui.water.properties;

public abstract class WaterHBondTranslucencyPropertyControls_generated extends molecule.ui.PropertyControls implements molecule.ui.water.signal.WaterHBondTranslucencyRaiser, star.event.EventController
{
	private static final long serialVersionUID = 1L;

	public  WaterHBondTranslucencyPropertyControls_generated(java.lang.String string, int int0, int int1, int int2)
	{
		super( string,int0,int1,int2);
	}
	 
	public void addNotify()
	{
		super.addNotify();
	}
	 
	public void raise_WaterHBondTranslucencyEvent()
	{
		(new molecule.ui.water.signal.WaterHBondTranslucencyEvent(this)).raise();
	}
	 
	public void removeNotify()
	{
		super.removeNotify();
	}
	 
}