/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package molecule.ui.protein.quaternary.signal;

public class ProteinQuaternaryHBondTranslucencyEvent extends star.event.Event
{
	private static final long serialVersionUID = 1L;

	public  ProteinQuaternaryHBondTranslucencyEvent(molecule.ui.protein.quaternary.signal.ProteinQuaternaryHBondTranslucencyEvent event)
	{
		super( event ) ;
	}
	 
	public  ProteinQuaternaryHBondTranslucencyEvent(molecule.ui.protein.quaternary.signal.ProteinQuaternaryHBondTranslucencyRaiser raiser)
	{
		super( raiser ) ;
	}
	 
	public  ProteinQuaternaryHBondTranslucencyEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public void raise()
	{
		raiseImpl();
	}
	 
}