/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package molecule.ui.protein.quaternary.signal;

public class ProteinQuaternaryFilterEvent extends star.event.Event
{
	private static final long serialVersionUID = 1L;

	public  ProteinQuaternaryFilterEvent(molecule.ui.protein.quaternary.signal.ProteinQuaternaryFilterEvent event)
	{
		super( event ) ;
	}
	 
	public  ProteinQuaternaryFilterEvent(molecule.ui.protein.quaternary.signal.ProteinQuaternaryFilterRaiser raiser)
	{
		super( raiser ) ;
	}
	 
	public  ProteinQuaternaryFilterEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public void raise()
	{
		raiseImpl();
	}
	 
}