/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package molecule.ui.protein.quaternary.signal;

public class ProteinQuaternaryTranslucencyEvent extends star.event.Event
{
	private static final long serialVersionUID = 1L;

	public  ProteinQuaternaryTranslucencyEvent(molecule.ui.protein.quaternary.signal.ProteinQuaternaryTranslucencyEvent event)
	{
		super( event ) ;
	}
	 
	public  ProteinQuaternaryTranslucencyEvent(molecule.ui.protein.quaternary.signal.ProteinQuaternaryTranslucencyRaiser raiser)
	{
		super( raiser ) ;
	}
	 
	public  ProteinQuaternaryTranslucencyEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public void raise()
	{
		raiseImpl();
	}
	 
}