/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package molecule.ui.protein.quaternary.signal;

public class ProteinQuaternaryApplyRenderingEvent extends star.event.Event
{
	private static final long serialVersionUID = 1L;

	public  ProteinQuaternaryApplyRenderingEvent(molecule.ui.protein.quaternary.signal.ProteinQuaternaryApplyRenderingEvent event)
	{
		super( event ) ;
	}
	 
	public  ProteinQuaternaryApplyRenderingEvent(molecule.ui.protein.quaternary.signal.ProteinQuaternaryApplyRenderingRaiser raiser)
	{
		super( raiser ) ;
	}
	 
	public  ProteinQuaternaryApplyRenderingEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public void raise()
	{
		raiseImpl();
	}
	 
}