/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package molecule.ui.protein.quaternary.signal;

public class ProteinQuaternaryRenderingModeEvent extends star.event.Event
{
	private static final long serialVersionUID = 1L;

	public  ProteinQuaternaryRenderingModeEvent(molecule.ui.protein.quaternary.signal.ProteinQuaternaryRenderingModeEvent event)
	{
		super( event ) ;
	}
	 
	public  ProteinQuaternaryRenderingModeEvent(molecule.ui.protein.quaternary.signal.ProteinQuaternaryRenderingModeRaiser raiser)
	{
		super( raiser ) ;
	}
	 
	public  ProteinQuaternaryRenderingModeEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public void raise()
	{
		raiseImpl();
	}
	 
}