/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package molecule.ui.water.signal;

public class WaterApplyRenderingEvent extends star.event.Event
{
	private static final long serialVersionUID = 1L;

	public  WaterApplyRenderingEvent(molecule.ui.water.signal.WaterApplyRenderingEvent event)
	{
		super( event ) ;
	}
	 
	public  WaterApplyRenderingEvent(molecule.ui.water.signal.WaterApplyRenderingRaiser raiser)
	{
		super( raiser ) ;
	}
	 
	public  WaterApplyRenderingEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public void raise()
	{
		raiseImpl();
	}
	 
}