/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package molecule.ui.water.signal;

public class WaterHBondSizeEvent extends star.event.Event
{
	private static final long serialVersionUID = 1L;

	public  WaterHBondSizeEvent(molecule.ui.water.signal.WaterHBondSizeEvent event)
	{
		super( event ) ;
	}
	 
	public  WaterHBondSizeEvent(molecule.ui.water.signal.WaterHBondSizeRaiser raiser)
	{
		super( raiser ) ;
	}
	 
	public  WaterHBondSizeEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public void raise()
	{
		raiseImpl();
	}
	 
}