/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package molecule.ui.water.signal;

public class WaterBondTranslucencyEvent extends star.event.Event
{
	private static final long serialVersionUID = 1L;

	public  WaterBondTranslucencyEvent(molecule.ui.water.signal.WaterBondTranslucencyEvent event)
	{
		super( event ) ;
	}
	 
	public  WaterBondTranslucencyEvent(molecule.ui.water.signal.WaterBondTranslucencyRaiser raiser)
	{
		super( raiser ) ;
	}
	 
	public  WaterBondTranslucencyEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public void raise()
	{
		raiseImpl();
	}
	 
}