/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package molecule.ui.water.signal;

public class WaterHBondTranslucencyEvent extends star.event.Event
{
	private static final long serialVersionUID = 1L;

	public  WaterHBondTranslucencyEvent(molecule.ui.water.signal.WaterHBondTranslucencyEvent event)
	{
		super( event ) ;
	}
	 
	public  WaterHBondTranslucencyEvent(molecule.ui.water.signal.WaterHBondTranslucencyRaiser raiser)
	{
		super( raiser ) ;
	}
	 
	public  WaterHBondTranslucencyEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public void raise()
	{
		raiseImpl();
	}
	 
}