/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package molecule.ui.water.signal;

public class WaterTranslucencyEvent extends star.event.Event
{
	private static final long serialVersionUID = 1L;

	public  WaterTranslucencyEvent(molecule.ui.water.signal.WaterTranslucencyEvent event)
	{
		super( event ) ;
	}
	 
	public  WaterTranslucencyEvent(molecule.ui.water.signal.WaterTranslucencyRaiser raiser)
	{
		super( raiser ) ;
	}
	 
	public  WaterTranslucencyEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public void raise()
	{
		raiseImpl();
	}
	 
}