/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package molecule.ui.water.signal;

public class WaterRenderingModeEvent extends star.event.Event
{
	private static final long serialVersionUID = 1L;

	public  WaterRenderingModeEvent(molecule.ui.water.signal.WaterRenderingModeEvent event)
	{
		super( event ) ;
	}
	 
	public  WaterRenderingModeEvent(molecule.ui.water.signal.WaterRenderingModeRaiser raiser)
	{
		super( raiser ) ;
	}
	 
	public  WaterRenderingModeEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public void raise()
	{
		raiseImpl();
	}
	 
}