/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package molecule.ui.water.signal;

public class WaterFilterEvent extends star.event.Event
{
	private static final long serialVersionUID = 1L;

	public  WaterFilterEvent(molecule.ui.water.signal.WaterFilterEvent event)
	{
		super( event ) ;
	}
	 
	public  WaterFilterEvent(molecule.ui.water.signal.WaterFilterRaiser raiser)
	{
		super( raiser ) ;
	}
	 
	public  WaterFilterEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public void raise()
	{
		raiseImpl();
	}
	 
}