/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package molecule.ui.adjust.center.protein.tertiary.signal;

public class CenterProteinTertiaryFilterEvent extends star.event.Event
{
	private static final long serialVersionUID = 1L;

	public  CenterProteinTertiaryFilterEvent(molecule.ui.adjust.center.protein.tertiary.signal.CenterProteinTertiaryFilterEvent event)
	{
		super( event ) ;
	}
	 
	public  CenterProteinTertiaryFilterEvent(molecule.ui.adjust.center.protein.tertiary.signal.CenterProteinTertiaryFilterRaiser raiser)
	{
		super( raiser ) ;
	}
	 
	public  CenterProteinTertiaryFilterEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public void raise()
	{
		raiseImpl();
	}
	 
}