/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package molecule.ui.protein.quaternary.signal;

public class ProteinQuaternaryHBondSizeEvent extends star.event.Event
{
	private static final long serialVersionUID = 1L;

	public  ProteinQuaternaryHBondSizeEvent(molecule.ui.protein.quaternary.signal.ProteinQuaternaryHBondSizeEvent event)
	{
		super( event ) ;
	}
	 
	public  ProteinQuaternaryHBondSizeEvent(molecule.ui.protein.quaternary.signal.ProteinQuaternaryHBondSizeRaiser raiser)
	{
		super( raiser ) ;
	}
	 
	public  ProteinQuaternaryHBondSizeEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public void raise()
	{
		raiseImpl();
	}
	 
}