/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package molecule.ui.protein.quaternary.signal;

public class ProteinQuaternarySSBondTranslucencyEvent extends star.event.Event
{
	private static final long serialVersionUID = 1L;

	public  ProteinQuaternarySSBondTranslucencyEvent(molecule.ui.protein.quaternary.signal.ProteinQuaternarySSBondTranslucencyEvent event)
	{
		super( event ) ;
	}
	 
	public  ProteinQuaternarySSBondTranslucencyEvent(molecule.ui.protein.quaternary.signal.ProteinQuaternarySSBondTranslucencyRaiser raiser)
	{
		super( raiser ) ;
	}
	 
	public  ProteinQuaternarySSBondTranslucencyEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public void raise()
	{
		raiseImpl();
	}
	 
}