/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package molecule.ui.protein.quaternary.signal;

public class ProteinQuaternarySelectionEvent extends star.event.Event
{
	private static final long serialVersionUID = 1L;

	public  ProteinQuaternarySelectionEvent(molecule.ui.protein.quaternary.signal.ProteinQuaternarySelectionEvent event)
	{
		super( event ) ;
	}
	 
	public  ProteinQuaternarySelectionEvent(molecule.ui.protein.quaternary.signal.ProteinQuaternarySelectionRaiser raiser)
	{
		super( raiser ) ;
	}
	 
	public  ProteinQuaternarySelectionEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public void raise()
	{
		raiseImpl();
	}
	 
}