/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package molecule.ui.protein.quaternary.signal;

public class ProteinQuaternarySSBondSizeEvent extends star.event.Event
{
	private static final long serialVersionUID = 1L;

	public  ProteinQuaternarySSBondSizeEvent(molecule.ui.protein.quaternary.signal.ProteinQuaternarySSBondSizeEvent event)
	{
		super( event ) ;
	}
	 
	public  ProteinQuaternarySSBondSizeEvent(molecule.ui.protein.quaternary.signal.ProteinQuaternarySSBondSizeRaiser raiser)
	{
		super( raiser ) ;
	}
	 
	public  ProteinQuaternarySSBondSizeEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public void raise()
	{
		raiseImpl();
	}
	 
}