/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package molecule.ui.protein.quaternary.signal;

public class ProteinQuaternarySizeEvent extends star.event.Event
{
	private static final long serialVersionUID = 1L;

	public  ProteinQuaternarySizeEvent(molecule.ui.protein.quaternary.signal.ProteinQuaternarySizeEvent event)
	{
		super( event ) ;
	}
	 
	public  ProteinQuaternarySizeEvent(molecule.ui.protein.quaternary.signal.ProteinQuaternarySizeRaiser raiser)
	{
		super( raiser ) ;
	}
	 
	public  ProteinQuaternarySizeEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public void raise()
	{
		raiseImpl();
	}
	 
}