/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package app.signal;

public class FileOpenEvent extends star.event.Event
{
	private static final long serialVersionUID = 1L;

	public  FileOpenEvent(app.signal.FileOpenEvent event)
	{
		super( event ) ;
	}
	 
	public  FileOpenEvent(app.signal.FileOpenRaiser raiser)
	{
		super( raiser ) ;
	}
	 
	public  FileOpenEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public void raise()
	{
		raiseImpl();
	}
	 
}