/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package app.signal;

public class ImportOpenEvent extends star.event.Event
{
	private static final long serialVersionUID = 1L;

	public  ImportOpenEvent(app.signal.ImportOpenEvent event)
	{
		super( event ) ;
	}
	 
	public  ImportOpenEvent(app.signal.ImportOpenRaiser raiser)
	{
		super( raiser ) ;
	}
	 
	public  ImportOpenEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public void raise()
	{
		raiseImpl();
	}
	 
}