/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package app.signal;

public class OpenMoleculeEvent extends star.event.Event
{
	private static final long serialVersionUID = 1L;

	public  OpenMoleculeEvent(app.signal.OpenMoleculeEvent event)
	{
		super( event ) ;
	}
	 
	public  OpenMoleculeEvent(app.signal.OpenMoleculeRaiser raiser)
	{
		super( raiser ) ;
	}
	 
	public  OpenMoleculeEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public void raise()
	{
		raiseImpl();
	}
	 
}