/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package app.signal;

public class RenderAllEvent extends star.event.Event
{
	private static final long serialVersionUID = 1L;

	public  RenderAllEvent(app.signal.RenderAllEvent event)
	{
		super( event ) ;
	}
	 
	public  RenderAllEvent(app.signal.RenderAllRaiser raiser)
	{
		super( raiser ) ;
	}
	 
	public  RenderAllEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public void raise()
	{
		raiseImpl();
	}
	 
}