/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package app.signal;

public class TrackGlassPaneEvent extends star.event.Event
{
	private static final long serialVersionUID = 1L;

	public  TrackGlassPaneEvent(app.signal.TrackGlassPaneEvent event)
	{
		super( event ) ;
	}
	 
	public  TrackGlassPaneEvent(app.signal.TrackGlassPaneRaiser raiser)
	{
		super( raiser ) ;
	}
	 
	public  TrackGlassPaneEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public void raise()
	{
		raiseImpl();
	}
	 
}