/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package app.signal;

public class ViewBackgroundColorEvent extends star.event.Event
{
	private static final long serialVersionUID = 1L;

	public  ViewBackgroundColorEvent(app.signal.ViewBackgroundColorEvent event)
	{
		super( event ) ;
	}
	 
	public  ViewBackgroundColorEvent(app.signal.ViewBackgroundColorRaiser raiser)
	{
		super( raiser ) ;
	}
	 
	public  ViewBackgroundColorEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public void raise()
	{
		raiseImpl();
	}
	 
}