/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package app.signal;

public class ViewStructurePropertiesEvent extends star.event.Event
{
	private static final long serialVersionUID = 1L;

	public  ViewStructurePropertiesEvent(app.signal.ViewStructurePropertiesEvent event)
	{
		super( event ) ;
	}
	 
	public  ViewStructurePropertiesEvent(app.signal.ViewStructureOptionsRaiser raiser)
	{
		super( raiser ) ;
	}
	 
	public  ViewStructurePropertiesEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public void raise()
	{
		raiseImpl();
	}
	 
}