/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package molecule.ui.protein.primary.signal;

public class ProteinPrimaryTranslucencyEvent extends star.event.Event
{
	private static final long serialVersionUID = 1L;

	public  ProteinPrimaryTranslucencyEvent(molecule.ui.protein.primary.signal.ProteinPrimaryTranslucencyEvent event)
	{
		super( event ) ;
	}
	 
	public  ProteinPrimaryTranslucencyEvent(molecule.ui.protein.primary.signal.ProteinPrimaryTranslucencyRaiser raiser)
	{
		super( raiser ) ;
	}
	 
	public  ProteinPrimaryTranslucencyEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public void raise()
	{
		raiseImpl();
	}
	 
}