/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package molecule.ui.protein.primary.signal;

public class ProteinPrimaryFilterEvent extends star.event.Event
{
	private static final long serialVersionUID = 1L;

	public  ProteinPrimaryFilterEvent(molecule.ui.protein.primary.signal.ProteinPrimaryFilterEvent event)
	{
		super( event ) ;
	}
	 
	public  ProteinPrimaryFilterEvent(molecule.ui.protein.primary.signal.ProteinPrimaryFilterRaiser raiser)
	{
		super( raiser ) ;
	}
	 
	public  ProteinPrimaryFilterEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public void raise()
	{
		raiseImpl();
	}
	 
}