/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package molecule.ui.protein.primary.signal;

public class ProteinPrimaryRenderingModeEvent extends star.event.Event
{
	private static final long serialVersionUID = 1L;

	public  ProteinPrimaryRenderingModeEvent(molecule.ui.protein.primary.signal.ProteinPrimaryRenderingModeEvent event)
	{
		super( event ) ;
	}
	 
	public  ProteinPrimaryRenderingModeEvent(molecule.ui.protein.primary.signal.ProteinPrimaryRenderingModeRaiser raiser)
	{
		super( raiser ) ;
	}
	 
	public  ProteinPrimaryRenderingModeEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public void raise()
	{
		raiseImpl();
	}
	 
}