/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package molecule.ui.adjust.center.protein.primary.signal;

public class CenterProteinPrimaryEvent extends molecule.ui.adjust.signal.SelectionEvent
{
	private static final long serialVersionUID = 1L;

	public  CenterProteinPrimaryEvent(molecule.ui.adjust.center.protein.primary.signal.CenterProteinPrimaryEvent event)
	{
		super( event ) ;
	}
	 
	public  CenterProteinPrimaryEvent(molecule.ui.adjust.center.protein.primary.signal.CenterProteinPrimaryRaiser raiser)
	{
		super( raiser ) ;
	}
	 
	public  CenterProteinPrimaryEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public void raise()
	{
		raiseImpl();
	}
	 
}