/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package molecule.ui.adjust.center.protein.primary.signal;

public class CenterProteinPrimarySelectionEvent extends molecule.ui.adjust.signal.SelectionEvent
{
	private static final long serialVersionUID = 1L;

	public  CenterProteinPrimarySelectionEvent(molecule.ui.adjust.center.protein.primary.signal.CenterProteinPrimarySelectionEvent event)
	{
		super( event ) ;
	}
	 
	public  CenterProteinPrimarySelectionEvent(molecule.ui.adjust.center.protein.primary.signal.CenterProteinPrimarySelectionRaiser raiser)
	{
		super( raiser ) ;
	}
	 
	public  CenterProteinPrimarySelectionEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public void raise()
	{
		raiseImpl();
	}
	 
}