/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package molecule.ui.nucleic.signal;

public class NucleicFilterEvent extends star.event.Event
{
	private static final long serialVersionUID = 1L;

	public  NucleicFilterEvent(molecule.ui.nucleic.signal.NucleicFilterEvent event)
	{
		super( event ) ;
	}
	 
	public  NucleicFilterEvent(molecule.ui.nucleic.signal.NucleicFilterRaiser raiser)
	{
		super( raiser ) ;
	}
	 
	public  NucleicFilterEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public void raise()
	{
		raiseImpl();
	}
	 
}