/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package molecule.ui.nucleic.signal;

public class NucleicApplyRenderingEvent extends star.event.Event
{
	private static final long serialVersionUID = 1L;

	public  NucleicApplyRenderingEvent(molecule.ui.nucleic.signal.NucleicApplyRenderingEvent event)
	{
		super( event ) ;
	}
	 
	public  NucleicApplyRenderingEvent(molecule.ui.nucleic.signal.NucleicApplyRenderingRaiser raiser)
	{
		super( raiser ) ;
	}
	 
	public  NucleicApplyRenderingEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public void raise()
	{
		raiseImpl();
	}
	 
}