/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package molecule.ui.nucleic.signal;

public class NucleicSelectionEvent extends star.event.Event
{
	private static final long serialVersionUID = 1L;

	public  NucleicSelectionEvent(molecule.ui.nucleic.signal.NucleicSelectionEvent event)
	{
		super( event ) ;
	}
	 
	public  NucleicSelectionEvent(molecule.ui.nucleic.signal.NucleicSelectionRaiser raiser)
	{
		super( raiser ) ;
	}
	 
	public  NucleicSelectionEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public void raise()
	{
		raiseImpl();
	}
	 
}