/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package molecule.ui.adjust.center.hetero.signal;

public class CenterHeteroSelectionEvent extends molecule.ui.adjust.signal.SelectionEvent
{
	private static final long serialVersionUID = 1L;

	public  CenterHeteroSelectionEvent(molecule.ui.adjust.center.hetero.signal.CenterHeteroSelectionEvent event)
	{
		super( event ) ;
	}
	 
	public  CenterHeteroSelectionEvent(molecule.ui.adjust.center.hetero.signal.CenterHeteroSelectionRaiser raiser)
	{
		super( raiser ) ;
	}
	 
	public  CenterHeteroSelectionEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public void raise()
	{
		raiseImpl();
	}
	 
}