/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package molecule.ui.signal;

public class RenderingInfoEvent extends star.event.Event
{
	private static final long serialVersionUID = 1L;

	public  RenderingInfoEvent(molecule.ui.signal.RenderingInfoEvent event)
	{
		super( event ) ;
	}
	 
	public  RenderingInfoEvent(molecule.ui.signal.RenderingInfoRaiser raiser)
	{
		super( raiser ) ;
	}
	 
	public  RenderingInfoEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public void raise()
	{
		raiseImpl();
	}
	 
}