/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package molecule.ui.jmol;

public abstract class MoleculeJmolContainer_generated extends javax.swing.JPanel implements app.signal.CloseMoleculeRaiser, star.event.EventController, star.event.Listener
{
	private star.event.Adapter adapter;
	private static final long serialVersionUID = 1L;

	public  MoleculeJmolContainer_generated()
	{
		super();
	}
	 
	public  MoleculeJmolContainer_generated(boolean boolean0)
	{
		super( boolean0);
	}
	 
	public  MoleculeJmolContainer_generated(java.awt.LayoutManager layoutManager, boolean boolean0)
	{
		super( layoutManager,boolean0);
	}
	 
	public  MoleculeJmolContainer_generated(java.awt.LayoutManager layoutManager)
	{
		super( layoutManager);
	}
	 
	public void addNotify()
	{
		super.addNotify();
		getAdapter().addHandled(molecule.ui.signal.RenderingInfoEvent.class);
		getAdapter().addHandled(molecule.ui.signal.AdjustInfoEvent.class);
	}
	 
	public void eventRaised(final star.event.Event event)
	{
		eventRaisedHandles(event);
	}
	 
	private void eventRaisedHandles(final star.event.Event event)
	{
		if( event.getClass().getName().equals( "molecule.ui.signal.RenderingInfoEvent" ) && event.isValid() ) 
		{
			 utils.Runner.runOnThread(new Runnable() { public void run() { 
			 long start = System.nanoTime();
			handleRenderingInfoRaiser( (molecule.ui.signal.RenderingInfoRaiser)event.getSource());
			 long end = System.nanoTime();
			 if( end - start > 500000000 ) { System.out.println( this.getClass().getName() + ".handleRenderingInfoRaiser "  + ( end-start )/1000000 ); } }},this,2);
		}if( event.getClass().getName().equals( "molecule.ui.signal.AdjustInfoEvent" ) && event.isValid() ) 
		{
			 utils.Runner.runOnThread(new Runnable() { public void run() { 
			 long start = System.nanoTime();
			handleAdjustInfoRaiser( (molecule.ui.signal.AdjustInfoRaiser)event.getSource());
			 long end = System.nanoTime();
			 if( end - start > 500000000 ) { System.out.println( this.getClass().getName() + ".handleAdjustInfoRaiser "  + ( end-start )/1000000 ); } }},this,2);
		}
	}
	 
	public star.event.Adapter getAdapter()
	{
		if( adapter == null )
		{
			adapter = new star.event.Adapter(this);
		}
		return adapter;
	}
	 
	abstract void handleAdjustInfoRaiser(molecule.ui.signal.AdjustInfoRaiser raiser);
	 
	abstract void handleRenderingInfoRaiser(molecule.ui.signal.RenderingInfoRaiser raiser);
	 
	public void raise_CloseMoleculeEvent()
	{
		(new app.signal.CloseMoleculeEvent(this)).raise();
	}
	 
	public void removeNotify()
	{
		super.removeNotify();
		getAdapter().removeHandled(molecule.ui.signal.RenderingInfoEvent.class);
		getAdapter().removeHandled(molecule.ui.signal.AdjustInfoEvent.class);
	}
	 
}