/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package molecule.ui.jmol;

public abstract class Viewer_generated extends javax.swing.JPanel implements star.event.EventController, star.event.Listener
{
	private star.event.Adapter adapter;
	private static final long serialVersionUID = 1L;

	public  Viewer_generated()
	{
		super();
	}
	 
	public  Viewer_generated(boolean boolean0)
	{
		super( boolean0);
	}
	 
	public  Viewer_generated(java.awt.LayoutManager layoutManager, boolean boolean0)
	{
		super( layoutManager,boolean0);
	}
	 
	public  Viewer_generated(java.awt.LayoutManager layoutManager)
	{
		super( layoutManager);
	}
	 
	public void addNotify()
	{
		super.addNotify();
		getAdapter().addHandled(app.signal.FileSaveImageEvent.class);
	}
	 
	public void eventRaised(final star.event.Event event)
	{
		eventRaisedHandles(event);
	}
	 
	private void eventRaisedHandles(final star.event.Event event)
	{
		if( event.getClass().getName().equals( "app.signal.FileSaveImageEvent" ) && event.isValid() ) 
		{
			 utils.Runner.runOnThread(new Runnable() { public void run() { 
			 long start = System.nanoTime();
			handleFileSaveImageRaiser( (app.signal.FileSaveImageRaiser)event.getSource());
			 long end = System.nanoTime();
			 if( end - start > 500000000 ) { System.out.println( this.getClass().getName() + ".handleFileSaveImageRaiser "  + ( end-start )/1000000 ); } }},this,2);
		}
	}
	 
	public star.event.Adapter getAdapter()
	{
		if( adapter == null )
		{
			adapter = new star.event.Adapter(this);
		}
		return adapter;
	}
	 
	abstract void handleFileSaveImageRaiser(app.signal.FileSaveImageRaiser raiser);
	 
	public void removeNotify()
	{
		super.removeNotify();
		getAdapter().removeHandled(app.signal.FileSaveImageEvent.class);
	}
	 
}