/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package molecule.ui.jmol;

public abstract class ViewerRenderWater_generated extends java.lang.Object implements app.signal.CloseMoleculeRaiser, star.event.EventController
{
	private star.event.Adapter adapter;
	private static final long serialVersionUID = 1L;

	public  ViewerRenderWater_generated()
	{
		super();
	}
	 
	public void addNotify()
	{
	}
	 
	public star.event.Adapter getAdapter()
	{
		if( adapter == null )
		{
			adapter = new star.event.Adapter(this);
		}
		return adapter;
	}
	 
	public void raise_CloseMoleculeEvent()
	{
		(new app.signal.CloseMoleculeEvent(this)).raise();
	}
	 
	public void removeNotify()
	{
	}
	 
}