/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package molecule.ui.protein.primary.properties;

public abstract class ProteinPrimaryTranslucencyPropertyControls_generated extends molecule.ui.PropertyControls implements molecule.ui.protein.primary.signal.ProteinPrimaryTranslucencyRaiser, star.event.EventController, star.event.Listener
{
	private static final long serialVersionUID = 1L;

	public  ProteinPrimaryTranslucencyPropertyControls_generated(java.lang.String string, int int0, int int1, int int2)
	{
		super( string,int0,int1,int2);
	}
	 
	public void addNotify()
	{
		super.addNotify();
		getAdapter().addHandled(molecule.ui.protein.tertiary.signal.ProteinTertiaryTranslucencyEvent.class);
	}
	 
	public void eventRaised(final star.event.Event event)
	{
		eventRaisedHandles(event);
	}
	 
	private void eventRaisedHandles(final star.event.Event event)
	{
		if( event.getClass().getName().equals( "molecule.ui.protein.tertiary.signal.ProteinTertiaryTranslucencyEvent" ) && event.isValid() ) 
		{
			 utils.Runner.runOnThread(new Runnable() { public void run() { 
			 long start = System.nanoTime();
			handleProteinTertiaryTranslucencyRaiser( (molecule.ui.protein.tertiary.signal.ProteinTertiaryTranslucencyRaiser)event.getSource());
			 long end = System.nanoTime();
			 if( end - start > 500000000 ) { System.out.println( this.getClass().getName() + ".handleProteinTertiaryTranslucencyRaiser "  + ( end-start )/1000000 ); } }},this,2);
		}
	}
	 
	abstract void handleProteinTertiaryTranslucencyRaiser(molecule.ui.protein.tertiary.signal.ProteinTertiaryTranslucencyRaiser raiser);
	 
	public void raise_ProteinPrimaryTranslucencyEvent()
	{
		(new molecule.ui.protein.primary.signal.ProteinPrimaryTranslucencyEvent(this)).raise();
	}
	 
	public void removeNotify()
	{
		super.removeNotify();
		getAdapter().removeHandled(molecule.ui.protein.tertiary.signal.ProteinTertiaryTranslucencyEvent.class);
	}
	 
}