/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package molecule.ui.adjust.center.protein.primary;

public abstract class CenterProteinPrimaryPanel_generated extends molecule.ui.AbstractMoleculeUI implements molecule.ui.adjust.center.protein.primary.signal.CenterProteinPrimaryRaiser, star.event.EventController, star.event.Listener
{
	private java.util.prefs.Preferences preferences = null;
	private static final long serialVersionUID = 1L;

	public  CenterProteinPrimaryPanel_generated()
	{
		super();
	}
	 
	public void addNotify()
	{
		super.addNotify();
		getAdapter().addHandled(molecule.ui.adjust.center.protein.primary.signal.CenterProteinPrimaryFilterEvent.class);
		getAdapter().addHandled(molecule.ui.adjust.center.protein.primary.signal.CenterProteinPrimarySelectionEvent.class);
	}
	 
	public void eventRaised(final star.event.Event event)
	{
		eventRaisedHandles(event);
	}
	 
	private void eventRaisedHandles(final star.event.Event event)
	{
		if( event.getClass().getName().equals( "molecule.ui.adjust.center.protein.primary.signal.CenterProteinPrimaryFilterEvent" ) && event.isValid() ) 
		{
			 utils.Runner.runOnThread(new Runnable() { public void run() { 
			 long start = System.nanoTime();
			handleCenterProteinPrimaryFilterRaiser( (molecule.ui.adjust.center.protein.primary.signal.CenterProteinPrimaryFilterRaiser)event.getSource());
			 long end = System.nanoTime();
			 if( end - start > 500000000 ) { System.out.println( this.getClass().getName() + ".handleCenterProteinPrimaryFilterRaiser "  + ( end-start )/1000000 ); } }},this,2);
		}if( event.getClass().getName().equals( "molecule.ui.adjust.center.protein.primary.signal.CenterProteinPrimarySelectionEvent" ) && event.isValid() ) 
		{
			 utils.Runner.runOnThread(new Runnable() { public void run() { 
			 long start = System.nanoTime();
			handleCenterProteinPrimarySelectionRaiser( (molecule.ui.adjust.center.protein.primary.signal.CenterProteinPrimarySelectionRaiser)event.getSource());
			 long end = System.nanoTime();
			 if( end - start > 500000000 ) { System.out.println( this.getClass().getName() + ".handleCenterProteinPrimarySelectionRaiser "  + ( end-start )/1000000 ); } }},this,2);
		}
	}
	 
	public java.util.prefs.Preferences getPreferences(java.lang.String name)
	{
		try
		{
			plugin.preferences.Preferences pref = (plugin.preferences.Preferences) plugin.Loader.getDefaultLoader().getPlugin(plugin.preferences.Preferences.class.getName(), plugin.preferences.PreferencesImplementation.class.getName());
			this.preferences = pref.getPreferences(name);
		}
		catch( plugin.PluginException ex )
		{
			ex.printStackTrace();
		}
		return preferences;
	}
	 
	public java.util.prefs.Preferences getPreferences()
	{
		if( preferences == null )
		{
			try
			{
				plugin.preferences.Preferences pref = (plugin.preferences.Preferences) plugin.Loader.getDefaultLoader().getPlugin(plugin.preferences.Preferences.class.getName(), plugin.preferences.PreferencesImplementation.class.getName());
				this.preferences = pref.getPreferences("molecule.ui.adjust.center.protein.primary.CenterProteinPrimaryPanel");
			}
			catch( plugin.PluginException ex )
			{
				ex.printStackTrace();
			}
		}
		return preferences;
	}
	 
	abstract void handleCenterProteinPrimaryFilterRaiser(molecule.ui.adjust.center.protein.primary.signal.CenterProteinPrimaryFilterRaiser raiser);
	 
	abstract void handleCenterProteinPrimarySelectionRaiser(molecule.ui.adjust.center.protein.primary.signal.CenterProteinPrimarySelectionRaiser raiser);
	 
	public void raise_CenterProteinPrimaryEvent()
	{
		(new molecule.ui.adjust.center.protein.primary.signal.CenterProteinPrimaryEvent(this)).raise();
	}
	 
	public void removeNotify()
	{
		super.removeNotify();
		getAdapter().removeHandled(molecule.ui.adjust.center.protein.primary.signal.CenterProteinPrimaryFilterEvent.class);
		getAdapter().removeHandled(molecule.ui.adjust.center.protein.primary.signal.CenterProteinPrimarySelectionEvent.class);
	}
	 
}